<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.54">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Composición Química de los Alimentos – LABORATORIO DE NUTRICIÓN ANIMAL</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../img/logo-unal-palmira2.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Sin resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../img/logo-unal-palmira2.svg" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">LABORATORIO DE NUTRICIÓN ANIMAL</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Buscar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Navegación de palanca" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Inicio</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-guías-laboratorio" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Guías laboratorio</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-guías-laboratorio">    
        <li>
    <a class="dropdown-item" href="../guias/analisis-alimentos-y-forrajes.html">
 <span class="dropdown-text">Análisis de alimentos y forrejes</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../guias/guia-composicion-quimica-alimentos.html">
 <span class="dropdown-text">Composición Química de los Alimentos</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="https://restec.com.co/" target="_blank"> 
<span class="menu-text">App</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta página</h2>
   
  <ul>
  <li><a href="#energía-bruta-eb" id="toc-energía-bruta-eb" class="nav-link active" data-scroll-target="#energía-bruta-eb">Energía Bruta (EB)</a></li>
  <li><a href="#referencias-bibliográficas" id="toc-referencias-bibliográficas" class="nav-link" data-scroll-target="#referencias-bibliográficas">Referencias Bibliográficas</a></li>
  <li><a href="#anexo-1.-determinación-del-contenido-en-materia-seca-mediante-calor" id="toc-anexo-1.-determinación-del-contenido-en-materia-seca-mediante-calor" class="nav-link" data-scroll-target="#anexo-1.-determinación-del-contenido-en-materia-seca-mediante-calor">Anexo 1. Determinación del Contenido en Materia Seca mediante Calor</a>
  <ul class="collapse">
  <li><a href="#material-necesario" id="toc-material-necesario" class="nav-link" data-scroll-target="#material-necesario">Material necesario</a></li>
  <li><a href="#procedimiento-de-materia-seca-inicial---ms-inicial" id="toc-procedimiento-de-materia-seca-inicial---ms-inicial" class="nav-link" data-scroll-target="#procedimiento-de-materia-seca-inicial---ms-inicial">Procedimiento de <strong>Materia Seca Inicial - MS inicial</strong></a></li>
  </ul></li>
  <li><a href="#determinación-de-la-materia-seca-analítica" id="toc-determinación-de-la-materia-seca-analítica" class="nav-link" data-scroll-target="#determinación-de-la-materia-seca-analítica">Determinación de la Materia Seca Analítica</a>
  <ul class="collapse">
  <li><a href="#material-necesario-1" id="toc-material-necesario-1" class="nav-link" data-scroll-target="#material-necesario-1">Material necesario</a></li>
  <li><a href="#preparación-de-los-crisoles" id="toc-preparación-de-los-crisoles" class="nav-link" data-scroll-target="#preparación-de-los-crisoles">Preparación de los crisoles</a></li>
  <li><a href="#procedimiento-de-ms-analítica" id="toc-procedimiento-de-ms-analítica" class="nav-link" data-scroll-target="#procedimiento-de-ms-analítica">Procedimiento de MS Analítica</a></li>
  </ul></li>
  <li><a href="#estimación-de-materia-seca-total---mst" id="toc-estimación-de-materia-seca-total---mst" class="nav-link" data-scroll-target="#estimación-de-materia-seca-total---mst">Estimación de Materia Seca Total - MST</a></li>
  <li><a href="#anexo-2.-determinación-de-cenizas" id="toc-anexo-2.-determinación-de-cenizas" class="nav-link" data-scroll-target="#anexo-2.-determinación-de-cenizas">Anexo 2. Determinación de Cenizas</a></li>
  <li><a href="#cenizas-totales" id="toc-cenizas-totales" class="nav-link" data-scroll-target="#cenizas-totales">Cenizas Totales</a>
  <ul class="collapse">
  <li><a href="#material-necesario-2" id="toc-material-necesario-2" class="nav-link" data-scroll-target="#material-necesario-2">Material necesario</a></li>
  <li><a href="#procedimiento" id="toc-procedimiento" class="nav-link" data-scroll-target="#procedimiento">Procedimiento</a></li>
  </ul></li>
  <li><a href="#cenizas-insolubles-en-hcl-1n-sílice" id="toc-cenizas-insolubles-en-hcl-1n-sílice" class="nav-link" data-scroll-target="#cenizas-insolubles-en-hcl-1n-sílice">Cenizas Insolubles en HCl 1N (Sílice)</a>
  <ul class="collapse">
  <li><a href="#material-necesario-3" id="toc-material-necesario-3" class="nav-link" data-scroll-target="#material-necesario-3">Material necesario</a></li>
  <li><a href="#procedimiento-1" id="toc-procedimiento-1" class="nav-link" data-scroll-target="#procedimiento-1">Procedimiento</a></li>
  </ul></li>
  <li><a href="#anexo-3.-determinación-de-extracto-etéreo" id="toc-anexo-3.-determinación-de-extracto-etéreo" class="nav-link" data-scroll-target="#anexo-3.-determinación-de-extracto-etéreo">Anexo 3. Determinación de Extracto Etéreo</a></li>
  <li><a href="#extracción-de-la-grasa-libre" id="toc-extracción-de-la-grasa-libre" class="nav-link" data-scroll-target="#extracción-de-la-grasa-libre">Extracción de la grasa libre</a>
  <ul class="collapse">
  <li><a href="#material-necesario-4" id="toc-material-necesario-4" class="nav-link" data-scroll-target="#material-necesario-4">Material necesario</a></li>
  <li><a href="#procedimiento-de-extracto-etéreo" id="toc-procedimiento-de-extracto-etéreo" class="nav-link" data-scroll-target="#procedimiento-de-extracto-etéreo">Procedimiento de Extracto Etéreo</a></li>
  </ul></li>
  <li><a href="#extracción-de-la-grasa-total" id="toc-extracción-de-la-grasa-total" class="nav-link" data-scroll-target="#extracción-de-la-grasa-total">Extracción de la grasa total</a>
  <ul class="collapse">
  <li><a href="#material-necesario-5" id="toc-material-necesario-5" class="nav-link" data-scroll-target="#material-necesario-5">Material necesario</a></li>
  <li><a href="#procedimiento-2" id="toc-procedimiento-2" class="nav-link" data-scroll-target="#procedimiento-2">Procedimiento</a></li>
  </ul></li>
  <li><a href="#anexo-4.-determinación-de-proteína-cruda" id="toc-anexo-4.-determinación-de-proteína-cruda" class="nav-link" data-scroll-target="#anexo-4.-determinación-de-proteína-cruda">Anexo 4. Determinación de Proteína Cruda</a>
  <ul class="collapse">
  <li><a href="#material-necesario-6" id="toc-material-necesario-6" class="nav-link" data-scroll-target="#material-necesario-6">Material necesario</a></li>
  <li><a href="#reactivos" id="toc-reactivos" class="nav-link" data-scroll-target="#reactivos">Reactivos</a></li>
  <li><a href="#procedimiento-3" id="toc-procedimiento-3" class="nav-link" data-scroll-target="#procedimiento-3">Procedimiento</a></li>
  <li><a href="#etapa-1-digestión-o-hidrólisis" id="toc-etapa-1-digestión-o-hidrólisis" class="nav-link" data-scroll-target="#etapa-1-digestión-o-hidrólisis">Etapa 1: Digestión o hidrólisis</a></li>
  <li><a href="#etapa-2-destilación" id="toc-etapa-2-destilación" class="nav-link" data-scroll-target="#etapa-2-destilación">Etapa 2: Destilación</a></li>
  <li><a href="#etapa-3-titulación" id="toc-etapa-3-titulación" class="nav-link" data-scroll-target="#etapa-3-titulación">Etapa 3: Titulación</a></li>
  </ul></li>
  <li><a href="#anexo-5.-análisis-de-van-soest" id="toc-anexo-5.-análisis-de-van-soest" class="nav-link" data-scroll-target="#anexo-5.-análisis-de-van-soest">Anexo 5. Análisis de Van Soest</a>
  <ul class="collapse">
  <li><a href="#determinación-de-la-fibra-detergente-neutra-fdn" id="toc-determinación-de-la-fibra-detergente-neutra-fdn" class="nav-link" data-scroll-target="#determinación-de-la-fibra-detergente-neutra-fdn">Determinación de la Fibra Detergente Neutra – FDN</a></li>
  <li><a href="#determinación-de-la-fibra-detergente-ácida-fda" id="toc-determinación-de-la-fibra-detergente-ácida-fda" class="nav-link" data-scroll-target="#determinación-de-la-fibra-detergente-ácida-fda">Determinación de la Fibra Detergente Ácida – FDA</a></li>
  <li><a href="#determinación-de-lignina-lda" id="toc-determinación-de-lignina-lda" class="nav-link" data-scroll-target="#determinación-de-lignina-lda">Determinación de Lignina – LDA</a></li>
  <li><a href="#ajuste-final-de-fdn-fda-y-lda" id="toc-ajuste-final-de-fdn-fda-y-lda" class="nav-link" data-scroll-target="#ajuste-final-de-fdn-fda-y-lda">Ajuste Final de FDN, FDA y LDA</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Composición Química de los Alimentos</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<hr>
<ol type="1">
<li>Texto relacionado con el ejercicio docente de la asignatura Nutrición Animal Básica</li>
</ol>
<ul>
<li>Composición Química de los Alimentos e Interpretación de resultados</li>
</ul>
<p>Luz Stella Muñoz Arboleda Profesora Asociada Departamento de Ciencia Animal</p>
<p>¹Nutrición Animal Básica. Profesora Luz Stella Muñoz Arboleda. Departamento de Ciencia Animal</p>
<hr>
<p>Abreviaturas</p>
<p>Las siguientes abreviaturas han sido utilizadas en las tablas.</p>
<p>En las tablas, los contenidos de nutrientes están expresados en materia seca</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Abreviatura</th>
<th>Descripción y Unidad</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>MS</td>
<td>Materia seca (%)</td>
</tr>
<tr class="even">
<td>MSi</td>
<td>MS inicial Muestra seca a 60°C. (%)</td>
</tr>
<tr class="odd">
<td>MSa</td>
<td>MS analítica muestra seca a 105°C. (%)</td>
</tr>
<tr class="even">
<td>MSt</td>
<td>MS total (MSi x MSa)/100. (%)</td>
</tr>
<tr class="odd">
<td>Cenizas</td>
<td>Minerales. (%)</td>
</tr>
<tr class="even">
<td>MO</td>
<td>Materia Orgánica =100 - % cenizas. (%)</td>
</tr>
<tr class="odd">
<td>EE</td>
<td>Extracto Etéreo (%)</td>
</tr>
<tr class="even">
<td>PC -</td>
<td>Proteína Cruda = N x 6.25</td>
</tr>
<tr class="odd">
<td>FDN</td>
<td>Fibra Detergente Neutra. /%)</td>
</tr>
<tr class="even">
<td>FDA</td>
<td>Fibra Detergente Ácida. (%)</td>
</tr>
<tr class="odd">
<td>LDA</td>
<td>Lignina Detergente Ácida. (%)</td>
</tr>
<tr class="even">
<td>EB</td>
<td>Energía Bruta (cal/g MS)</td>
</tr>
</tbody>
</table>
<hr>
<p>ASPECTOS A TENER EN CUENTA PARA LOS ANALISIS DE COMPOSICION QUIMICA DE LOS ALIMENTOS E INTERPRETACIÓN DE RESULTADOS DE LABORATORIO¹</p>
<p>Todos los alimentos están compuestos por dos elementos: Agua y Materia Seca. La proporción de cada uno de estos, dependerá del tipo de alimento, es decir habrá alimentos con mayor contenido de agua que otros, en la tabla 1 se presentan ejemplos relacionados con la cantidad de agua y materia seca de algunas materias primas (alimentos) utilizados en alimentación animal.</p>
<p>Tabla 1. Contenidos de agua y materia seca - MS de alimentos utilizados en alimentación animal</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Alimentos</th>
<th>Agua - Humedad (%)</th>
<th>MS (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Forrajes verdes¹</td>
<td>70-95</td>
<td>5-30</td>
</tr>
<tr class="even">
<td>Henos¹</td>
<td>15-20</td>
<td>80-85</td>
</tr>
<tr class="odd">
<td>Concentrados comerciales¹</td>
<td>6-10</td>
<td>90-94</td>
</tr>
<tr class="even">
<td>Semillas de cereales²</td>
<td>9-14</td>
<td>86-91</td>
</tr>
<tr class="odd">
<td>Tortas de oleaginosas²</td>
<td>8-12</td>
<td>88-92</td>
</tr>
</tbody>
</table>
<p>Información tomada de análisis realizados en el laboratorio de Nutrición Animal en la asignatura Nutrición Animal Básica. Sauvant et al., 2002.</p>
<p>En este grupo de materias primas, se encuentran unas con altos contenidos de humedad y poca materia seca (Forrajes Verdes) y otras con bajos contenidos de humedad y alta materia seca.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./img/Forrajes.png" class="img-fluid figure-img"></p>
<figcaption>Forrajes</figcaption>
</figure>
</div>
<p>Figura 1. Los forrajes contienen menos materia seca (MS) que los granos. Dibujo de Martínez Lasso (2018)¹. ¹ Estudiante Ingeniería Agronómica</p>
<p>Los henos, concentrados comerciales, semillas de cereales y tortas de oleaginosas, por su alto contenido de materia seca, se les puede llamar materias primas concentradas.</p>
<p>Forrajes verdes: Los contenidos de agua de un forraje verde dependen en gran medida del tipo de forraje, es decir, una planta acuática como: el buchón de agua Eichhornia crassipes, la azola Azolla salvinia, o la salvivia Salvinia molesta pueden contener hasta 95% de agua.</p>
<hr>
<p>En épocas de gran sequía, los forrajes pueden presentar contenidos altos de Materia Seca, que pueden llegar hasta 40%. De igual manera los forrajes arbustivos de manera general se caracterizan por tener contenidos de Materia Seca más elevados que los forrajes para pastoreo. (Tabla 2).</p>
<p>Tabla 2. Contenidos de materia seca de diferentes forrajes¹.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Nombre científico</th>
<th>Nombre Común</th>
<th>MS (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cynodon plectostachius</td>
<td>Pasto estrella</td>
<td>25,2</td>
</tr>
<tr class="even">
<td>Trichantera gigantea</td>
<td>Nacedero</td>
<td>13,4</td>
</tr>
<tr class="odd">
<td>Arachis pintoi</td>
<td>Maní forrajero</td>
<td>18,2</td>
</tr>
<tr class="even">
<td>Salvinia</td>
<td>Salvinia molesta</td>
<td>7,0</td>
</tr>
<tr class="odd">
<td>Caryodendron orinocense</td>
<td>Inchi</td>
<td>37,5</td>
</tr>
<tr class="even">
<td>Terminalia catappa</td>
<td>Almendro</td>
<td>37,0</td>
</tr>
<tr class="odd">
<td>Erytrina variegata</td>
<td>Erytrina</td>
<td>21,7</td>
</tr>
<tr class="even">
<td>Sterculia apetala</td>
<td>Cacao de monte</td>
<td>43,6</td>
</tr>
<tr class="odd">
<td>Gliricidia sepium</td>
<td>Matarratón</td>
<td>15,8</td>
</tr>
<tr class="even">
<td>Pueraria phaseoloides</td>
<td>Kudzu</td>
<td>20,4</td>
</tr>
<tr class="odd">
<td>Pithecellobium dulce</td>
<td>Orejero</td>
<td>34,5</td>
</tr>
</tbody>
</table>
<p>Información tomada de análisis realizados en el laboratorio de Nutrición Animal en la asignatura Nutrición Animal Básica</p>
<p>Conocer el contenido de Materia Seca de los alimentos es de gran importancia, puesto que en esta se encuentran todos los nutrientes (proteínas, lípidos, almidones, azucares, etc). De esta manera se puede estimar, por ejemplo, cual es el consumo de proteína con el suministro de un forraje:</p>
<p>Por ejemplo, si tenemos 1kg de pasto estrella Cynodon plectostachius como Forraje Verde F.V. y lo comparamos con 1 kg de este mismo, pero en forma de heno, el kg heno aportaría más nutrientes al animal que el kg de Forraje verde, pero su composición química sería la misma (si se trata del mismo forraje, es decir del mismo sitio cortado simultáneamente, un parte para ser analizado como Forraje Verde y otra parte, a la cual se le hace el proceso de henificación) pues la determinación de los nutrientes en el laboratorio es en base seca.</p>
<p>Pasto estrella como FV 20% MS; 10% Proteína Cruda – P.C Pasto estrella como heno 85% MS; 10% Proteína Cruda</p>
<p>1 kg de heno equivale a 0.85 kg (850 g) de MS y a su vez, a 0.085 kg (85 g) de P.C. 1 kg de F.V. equivale a 0.20 kg (200 g) de MS y a su vez, a 0.020 kg (20 g) de P.C.</p>
<p>Que cantidad de muestra se debe recolectar para los análisis de Weende y de Van Soest: Para la realización de todos los análisis se debe contar al menos con 15 g de material seco (60 °C) en harina. Es decir que la cantidad de muestra a recolectar depende del contenido de humedad de esta.</p>
<hr>
<p>Si trae una muestra de forraje verde entre 200 y 300 g, y se estima que la MS de este es aproximadamente 20%, al final obtendría entre 40 y 60 g de material para los respectivos análisis.</p>
<p>Pero si se trae una muestra de torta de soya, será suficiente entre 50 y 100 g, se estima su MS como 90%, al final se podría obtener entre 45 y 90 g de material seco para ser analizado. Lo ideal sería contar con al menos 50 g de harina de la muestra, pues en algunas ocasiones se hace necesario realizar repeticiones del análisis.</p>
<p>Materia Seca</p>
<p>La determinación del contenido de Materia Seca es muy importante en nutrición animal, dado que en esta se encuentran todos los nutrientes. La determinación de los diferentes nutrientes a nivel de Laboratorio se realizará en la materia seca, por lo que todas las muestras deben ser secadas para conocer su contenido de humedad. Y los valores generados de los diferentes nutrientes serán expresados en porcentaje de la MS, por ejemplo, si se determina que el pasto estrella tiene un contenido de tiene un contenido de MS de 35%, esto indica que en:</p>
<p>100 g de FV hay 35 g de MS o que en 100 kg de FV hay 35 kg de MS Y se dice que la proteína cruda es 10%, y de cenizas (minerales) es 11%, esto indica que: En 100 g de MS hay 10 g de proteína cruda o En 100 kg de MS hay 10 kg de proteína cruda En 100 g de MS hay 11 g de ceniza o En 100 kg de MS hay 11 g de cenizas</p>
<p>La importancia de la MS en Nutrición Animal igualmente se debe a que los consumos por parte del animal de una dieta, forraje o alimento siempre se estiman en kg de MS, para luego con la información del contenido de MS de estos se estime cuanto sería en base fresca (cuantos kg debo suministrar (pesar) de la dieta, el forraje o alimento.</p>
<p>Métodos de Análisis: Existen diferentes métodos de secado según el contenido de humedad de la muestra a analizar (Leterme y Estrada, 2010). Aunque existen diferentes métodos de secado, actualmente en el laboratorio de Nutrición Animal, se está realizando en estufa analítica. (Anexo 2 Determinación de MS inicial, y Analítica).</p>
<p>Las muestras con alto contenido de humedad deben secarse inicialmente a bajas temperaturas (40-60°C) para eliminar un gran contenido de esta, sin que se afecte su composición química, es decir, sin que los nutrientes presentes en esta, se dañen, igualmente deben ser secadas para lograr ser molidas a talla de partícula de 1 mm, para posteriores análisis de nutrientes. La reacción de pardeamiento que se produce por interacción entre los aminoácidos y los azúcares reductores, libera agua durante la deshidratación y se acelera a temperaturas elevadas. Los alimentos ricos en proteínas y azúcares reductores deben, por ello, desecarse con precaución, de preferencia en una estufa de vacío a 60°C. (Hart, 1991).</p>
<p>El secado a estas temperaturas evita pérdidas sensibles de carbohidratos solubles y formación de complejos indigestibles proteína-carbohidratos. La formación de proteínas insolubles y productos de Maillard incrementa con la temperatura (Van Soest, 1994).</p>
<hr>
<p>La determinación de secado en estufa se basa en la pérdida de peso de la muestra por evaporación del agua. El principio operacional del método de determinación de humedad utilizando estufa y balanza analíticas, desecadores, incluye la preparación de la muestra, pesado, secado, enfriado y pesado nuevamente de la muestra. (Leterme y Estrada, 2010).</p>
<p>El agua en los tejidos vegetales y animales, puede decirse que existe en dos formas generales: “agua libre” Y “agua ligada”. El agua libre o absorbida, que es la forma predominante, se libera con gran facilidad. El agua ligada a las proteínas y a las moléculas de sacáridos y absorbida sobre la superficie de las partículas coloidales. (Hart, 1991). El secado de la muestra a 60°C, solo logra sacar el agua libre que es aproximadamente un 90%, por lo que la muestra quedara con un contenido de agua de 10%, que corresponde al agua ligada.</p>
<p>Después de este secado inicial la muestra puede ser molida a un tamaño de partícula de 1 mm, tamaño que se requiere para la determinación de otros análisis, como proteína cruda, extracto etéreo, etc.</p>
<p>La determinación de la Materia Seca a 60°C es lo que se conoce como Materia Seca Inicial (anexo 1).</p>
<p>Para lograr sacar el contenido de agua ligada de la muestra, se debe llevar una parte (aproximadamente 5 g) de la muestra secada a 60°C a temperaturas más altas, a 105°C, es lo que conocemos como determinación de Materia Seca Analítica, la cual se utilizara como un factor de corrección para la materia seca inicial y de esta manera conocer el contenido total de materia seca de la muestra, como se indica a continuación:</p>
<p>MS total = Materia Seca Inicial x Materia Seca Analítica 100</p>
<p>En la tabla 3, se presentan ejemplos de valores de Materia Seca inicial, Materia Seca Analítica y Materia Seca Total de varias materias primas utilizadas en alimentación animal.</p>
<p>Tabla 3. Determinaciones de MS inicial y analitica¹, estimación de MS total de alginas materias primas utilizadas para alimentación animal</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Alimentos</th>
<th>Materia Seca Inicial (%)</th>
<th>Materia Seca Analítica (%)</th>
<th>Materia Seca Total (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Leucaena leucocephala</td>
<td>25.8</td>
<td>93.4</td>
<td>24.9</td>
</tr>
<tr class="even">
<td>Guinea Panicum maximum</td>
<td>21.8</td>
<td>95.5</td>
<td>20.8</td>
</tr>
<tr class="odd">
<td>Brachiaria Decumbens</td>
<td>24.3</td>
<td>95.7</td>
<td>23.2</td>
</tr>
<tr class="even">
<td>Puntero Hyparrhenia rufa</td>
<td>33.7</td>
<td>93.0</td>
<td>32.4</td>
</tr>
<tr class="odd">
<td>Kikuyo Pennisetum clandestinum</td>
<td>15.3</td>
<td>94.1</td>
<td>14.4</td>
</tr>
<tr class="even">
<td>Semillas de Girasol</td>
<td>—</td>
<td>93.0</td>
<td>93.0</td>
</tr>
<tr class="odd">
<td>Maíz amarillo (grano)</td>
<td>—</td>
<td>88.3</td>
<td>88.3</td>
</tr>
<tr class="even">
<td>Torta de Soya²</td>
<td>—</td>
<td>87.8</td>
<td>87.8</td>
</tr>
<tr class="odd">
<td>Harina de pescado²</td>
<td>—</td>
<td>91.7</td>
<td>91.7</td>
</tr>
</tbody>
</table>
<p>’información generada en el laboratorio de Nutrición Animal, por estudiantes de la asignatura de Nutrición Animal Básica. 2Sauvant et al., 2002. No es necesario realizar esta determinación, pues su bajo contenido de humedad, permite molienda</p>
<hr>
<p>Las materias primas con un bajo contenido de agua, como por ejemplo la torta se soya o las semillas de girasol, pueden ser llevadas directamente a molienda, y se les determina el contenido de materia seca, llevando una muestra (5 g) de estas a 105°C, temperatura que logra sacar el 100% de la humedad y directamente se encontraría su valor total de materia seca.</p>
<p>Si solo se necesita conocer el valor de materia seca de un forraje o una materia prima rica en agua, como las frutas, es decir, no se necesita realizar análisis de sus nutrientes, la muestra rica en agua, puede ser llevada directamente a 105°C para la determinación de su materia seca, es decir no se necesita realizar la MS Inicial, que solo se realiza para muestras con altos contenidos de humedad (agua).</p>
<p>Cenizas o Minerales</p>
<p>Las cenizas de un alimento son un término analítico equivalente al residuo inorgánico (minerales) que queda después de calcinar la materia orgánica. Las cenizas normalmente, no son las mismas sustancias inorgánicas presentes en el alimento original, debido a las perdidas por volatilización (Na, Cl, K, Py S) o a las interacciones químicas entre los constituyentes.</p>
<p>Método de Análisis: El carbonato potásico se volatiliza apreciablemente a 700°C y se pierde casi por completo a 900°C. El carbonato sódico permanece inalterado a 700°C, pero sufre pérdidas considerables a 900°C. En general, la temperatura adecuada de la mufla son 500°C. Sin embargo, los cloruros, pueden volatilizarse a esta temperatura (anexo 2).</p>
<p>Un alto contenido de minerales en una materia prima, puede afectar de manera negativa la digestibilidad de esta. En la tabla 4, se presenta el contenido de cenizas de diferentes materias primas.</p>
<p>Tabla 4. Contenidos de cenizas¹, y estimación de materia orgánica – MO de materias primas</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Alimentos</th>
<th>Cenizas (%)</th>
<th>Materia Orgánica (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Leucaena</td>
<td>7.4</td>
<td>92.6</td>
</tr>
<tr class="even">
<td>Guinea</td>
<td>11.9</td>
<td>88.1</td>
</tr>
<tr class="odd">
<td>Brachiaria decumbens</td>
<td>12.0</td>
<td>88.0</td>
</tr>
<tr class="even">
<td>Puntero</td>
<td>13.0</td>
<td>87.0</td>
</tr>
<tr class="odd">
<td>Pasto Kikuyo</td>
<td>11.4</td>
<td>88.6</td>
</tr>
<tr class="even">
<td>Semillas de Girasol</td>
<td>3.4</td>
<td>96.6</td>
</tr>
<tr class="odd">
<td>Maíz amarillo (grano)</td>
<td>1.4</td>
<td>98.6</td>
</tr>
<tr class="even">
<td>Torta de Soya²</td>
<td>6.4</td>
<td>93.6</td>
</tr>
<tr class="odd">
<td>Harina de pescado²</td>
<td>16.2</td>
<td>91.1</td>
</tr>
</tbody>
</table>
<p>’información generada en el laboratorio de Nutrición Animal, por estudiantes de la asignatura de Nutrición Animal Básica. Sauvant et al., 2002</p>
<p>En general, el contenido de cenizas en los forrajes puede variar entre 7 y 15%, con algunas excepciones como, por ejemplo, el nacedero, <em>Trichantera gigantea</em>, que presenta alto contenido de cenizas (17-25%). Otra materia prima utilizada en la formulación de dietas para</p>
<hr>
<p>animales, como es, la harina de huesos puede contener 70% de cenizas, los minerales presentes en esta, son principalmente Calcio y fosforo.</p>
<p>Para estimar la Materia Orgánica de una materia prima, debemos tener en cuenta que: la materia seca de una muestra, está formada por materia seca orgánica y materia seca inorgánica.</p>
<p>Por ejemplo, en el forraje de <em>Brachiaria decumbens</em>, el contenido de cenizas es 12%, por lo que el contenido de cenizas de una muestra servirá para estimar el contenido de Materia Orgánica de esta:</p>
<p>Materia Orgánica</p>
<p>Materia Seca 100</p>
<p>Materia inorgánica (cenizas) 12</p>
Materia<sub>Seca</sub>(100) =
<span class="math display">\[\begin{cases} Materia~Orgánica \\ Materia~inorgánica~(cenizas) \textbf{12} \end{cases}\]</span>
<p>Para estimar el contenido de Materia Orgánica se utiliza la siguiente formula:</p>
<p>% Materia Orgánica = 100 - % cenizas</p>
<p>% MO <em>Brachieria decumbens</em> = 100 – 12 = 88% de Materia Orgánica</p>
<p>Las cenizas se utilizan muchas veces para la determinación de constituyentes individuales, por ejemplo, cloruros, fosfatos, calcio y hierro. (Kirk et al, 1996). Estas determinaciones de los diferentes minerales (perfil de minerales) pueden realizarse por métodos de espectrofotometría de absorción atómica.</p>
<p>Un alto contenido de cenizas o minerales implica menos contenido de Materia Orgánica en un alimento y esto a su vez se ve reflejado en una menor digestibilidad de la Materia Seca. Las cenizas junto con la Fibra son elementos de la composición química que afectan la digestibilidad. Como se mencionó anteriormente cuando estos presentan contenidos altos de cenizas, la digestibilidad podría ser más baja, que para aquellas materias primas con contenidos de estos nutrientes más bajos (tabla 5).</p>
<p>Tabla 5. Contenido de materia seca, cenizas y digestibilidad de la MS de forrajes¹. Helecho de agua <em>Azolla sp</em>, <em>Bore Alocasia macrorhyza Morera Morus alba</em>, <em>Nacedero Trichatera gigantea Salvinia Salvinia molesta</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">AZOLLA</th>
<th style="text-align: center;">BORE</th>
<th style="text-align: center;">MORERA</th>
<th style="text-align: center;">NACEDERO</th>
<th style="text-align: center;">SALVINIA</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>MS Inicial (%)</td>
<td style="text-align: center;">7.0</td>
<td style="text-align: center;">14.5</td>
<td style="text-align: center;">26.0</td>
<td style="text-align: center;">21.0</td>
<td style="text-align: center;">7.0</td>
</tr>
<tr class="even">
<td>MS Analítica (%)</td>
<td style="text-align: center;">89.9</td>
<td style="text-align: center;">92.9</td>
<td style="text-align: center;">93.4</td>
<td style="text-align: center;">93.1</td>
<td style="text-align: center;">87.9</td>
</tr>
<tr class="odd">
<td>Cenizas (%)</td>
<td style="text-align: center;">20.6</td>
<td style="text-align: center;">9.8</td>
<td style="text-align: center;">12.8</td>
<td style="text-align: center;">16.3</td>
<td style="text-align: center;">19.8</td>
</tr>
<tr class="even">
<td>Digestibilidad² (%)</td>
<td style="text-align: center;">36.4</td>
<td style="text-align: center;">50.7</td>
<td style="text-align: center;">48.2</td>
<td style="text-align: center;">33.0</td>
<td style="text-align: center;">32.7</td>
</tr>
</tbody>
</table>
<p>’Ruiz et al., 2005. Digestibilidad enzimática en cerdos</p>
<p>Extracto Etéreo</p>
<hr>
<p>La determinación del Extracto Etéreo- EE o grasa total, no caracteriza adecuadamente el contenido de grasa de los alimentos, sin embargo, sigue siendo el método oficial. El término extracto etéreo se refiere al conjunto de las sustancias extraídas que incluyen, además de los ésteres de los ácidos grasos como el glicerol, a los fosfolípidos, las lecitinas, los esteroles, las ceras, los ácidos grasos libres, los carotenos, las clorofilas y otros pigmentos (anexo 3)</p>
<p>Los contenidos de extracto etéreo de un forraje son en general bajos, con algunas excepciones el contenido de grasa de los vegetales no es significativo. Una gran parte de extracto etéreo en los forrajes está compuesta por sustancias no saponificable (ceras, clorofila, cutina, etc).</p>
<p>En la tabla 6, se presentan datos del contenido de extracto etéreo de algunas materias primas.</p>
<p>Tabla 6. Contenidos de extracto etéreo de materias primas para alimentación animal</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Alimentos</th>
<th>Extracto Etéreo (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Leucaena</td>
<td>4.6</td>
</tr>
<tr class="even">
<td>Guinea</td>
<td>1.6</td>
</tr>
<tr class="odd">
<td>Brachiaria decumbens</td>
<td>3.0</td>
</tr>
<tr class="even">
<td>Puntero</td>
<td>2.3</td>
</tr>
<tr class="odd">
<td>Pasto kikuyo</td>
<td>3.9</td>
</tr>
<tr class="even">
<td>Semillas de Girasol</td>
<td>44.6</td>
</tr>
<tr class="odd">
<td>Maíz amarillo (grano)</td>
<td>6.9</td>
</tr>
<tr class="even">
<td>Torta de Soya²</td>
<td>1.9</td>
</tr>
<tr class="odd">
<td>Harina de pescado²</td>
<td>9.5</td>
</tr>
</tbody>
</table>
<p>’información generada en el laboratorio de Nutrición Animal, por estudiantes de la asignatura de Nutrición Animal Básica. 2Sauvant et al., 2002</p>
<p>El contenido de lípidos de alimentos es muy variable, desde menos del 1% en algunos productos hasta un 100% en algunas grasas. Una gran parte de extracto etéreo en los forrajes está compuesta por sustancias no saponificable (ceras, clorofila, cutina, etc) La mayoría de los lípidos en los forrajes se encuentra en los cloroplastos y su proporción del peso seco de la planta disminuye a medida que la planta madura.</p>
<p>Como observamos en la tabla 6, los lípidos representan una fracción muy baja de la materia seca de los forrajes (1.6 – 4.6%).</p>
<p>Los granos de oleaginosas como, por ejemplo, soya, girasol y palmiste, se caracterizan por sus altos contenidos en grasas-extracto etéreo, entre 20 y 40% de la MS. Estos granos tienen un alto valor energético y proteico alto, por lo que algunos autores también las llaman oleoproteaginosas.</p>
<p>Las materias primas de origen animal tienen menos contenidos de grasa que las oleaginosas, en la tabla 7 se presentan algunas materias primas de origen animal con sus contenidos de</p>
<hr>
<p>materia seca y grasas, representados como g MS /kg de producto y g de grasas / kg de MS, que son unidades en las que también son presentados los contenidos de nutrientes en un alimento.</p>
<p>Por ejemplo, la Harina de Pescado Graso con 920 g MS/ kg de Producto, equivaldría en porcentaje a 92% y los 96 g de grasas / kg de MS, equivaldrían a 9.6% de grasa.</p>
<p>Tabla 7. Composición en materia seca (g MS/ kg) y grasas en productos de origen animal (g/kg MS)</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Alimentos¹</th>
<th>Materia Seca</th>
<th>Materias Grasas</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Harina de Pescado Graso 65</td>
<td>920</td>
<td>96</td>
</tr>
<tr class="even">
<td>Harina de Pescado Magro 65</td>
<td>920</td>
<td>55</td>
</tr>
<tr class="odd">
<td>Harina de Carne Grasa 55</td>
<td>930</td>
<td>99</td>
</tr>
<tr class="even">
<td>Harina de Carne Magra 55</td>
<td>930</td>
<td>50</td>
</tr>
<tr class="odd">
<td>Leche descremada Seca</td>
<td>950</td>
<td>8</td>
</tr>
<tr class="even">
<td>Suero de Leche descremado</td>
<td>960</td>
<td>9</td>
</tr>
</tbody>
</table>
<ol type="1">
<li>Gadoud et al., 1992.</li>
</ol>
<p>A manera de ejemplo y referente, se presentan en la tabla 8, alimentos utilizados en alimentación humana</p>
<p>Tabla 8. Composición en grasas en alimentos para humanos (%)</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Alimentos¹</th>
<th>Materia Seca</th>
<th>Materias Grasas</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Aceites y Mantecas</td>
<td>100</td>
<td>100</td>
</tr>
<tr class="even">
<td>Mantequilla y Margarina</td>
<td>84-86</td>
<td>80</td>
</tr>
<tr class="odd">
<td>Almendras</td>
<td>94</td>
<td>54</td>
</tr>
<tr class="even">
<td>Nueces</td>
<td>96</td>
<td>64</td>
</tr>
<tr class="odd">
<td>Leche</td>
<td>10</td>
<td>3.5-4.3</td>
</tr>
<tr class="even">
<td>Huevos</td>
<td>25</td>
<td>12</td>
</tr>
<tr class="odd">
<td>Cereales</td>
<td></td>
<td>3-5</td>
</tr>
<tr class="even">
<td><strong>Frutas y Vegetales</strong></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Manzana</td>
<td>15</td>
<td>0.4</td>
</tr>
<tr class="even">
<td>Naranja</td>
<td>13</td>
<td>0.2</td>
</tr>
<tr class="odd">
<td>Aguacate</td>
<td>25</td>
<td>26.4</td>
</tr>
<tr class="even">
<td>Maíz</td>
<td>88</td>
<td>1.2</td>
</tr>
<tr class="odd">
<td>Coco</td>
<td>54</td>
<td>35</td>
</tr>
<tr class="even">
<td><strong>Productos del mar</strong></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Bacalao</td>
<td>20-30</td>
<td>1.4</td>
</tr>
<tr class="even">
<td>Caviar</td>
<td>20-30</td>
<td>15.5</td>
</tr>
<tr class="odd">
<td>Sardinas</td>
<td>20-30</td>
<td>13.9</td>
</tr>
</tbody>
</table>
<ol start="2" type="1">
<li>’Gadoud et al., 1982.</li>
</ol>
<p><br></p>
<p><strong>Método de análisis</strong></p>
<p>En la determinación del extracto etéreo se utiliza un solvente orgánico, en nuestro caso, éter de petróleo, que es el que solubiliza las grasas. El método Soxhlet permite extraer la grasa libre, pero no la ligada a proteínas o carbohidratos solubles. Para liberar la grasa ligada, se necesita realizar una hidrólisis ácida antes de extraer la grasa.</p>
<p>Para la determinación de extracto etéreo de materias primas de origen animal, es necesario tener en cuenta que estas materias primas por sus altos contenidos de proteína, presentan grasas ligadas a esta, que no pueden ser extraídas con el solvente orgánico. Para este tipo de materias primas, se hace necesario realizar un hidrólisis ácida para romper el enlace Grasa- Proteína o Grasa-Carbohidratos, antes de utilizar el solvente orgánico.</p>
<p>Estas materias primas también tienen grasas libres, que son las que el éter de petróleo puede solubilizar, es por esto, que podríamos encontrar contenidos bajos de extracto etéreo, cuando no se les realiza la hidrólisis previa con ácido clorhídrico.</p>
<p>En la tabla 9. Presentamos contenidos de extracto etéreo de materias primas a las que se les realizó la determinación de extracto etéreo sin y con hidrólisis previa.</p>
<p>Tabla 9. Materias primas de origen animal sin y con hidrólisis antes de la determinación de extracto etéreo -EE.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 37%">
<col style="width: 41%">
</colgroup>
<thead>
<tr class="header">
<th>Materia Prima</th>
<th>% EE</th>
<th>% EE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>Sin Hidrolisis ácida</td>
<td>Con Hidrolisis Acida</td>
</tr>
<tr class="even">
<td>Pastel de carne</td>
<td>1.2</td>
<td>22.7</td>
</tr>
<tr class="odd">
<td>Queso blando</td>
<td>3.3</td>
<td>26.1</td>
</tr>
<tr class="even">
<td>Leche entera en polvo</td>
<td>1.1</td>
<td>25.7</td>
</tr>
<tr class="odd">
<td>Pastel de hígado</td>
<td>17.1</td>
<td>20.3</td>
</tr>
<tr class="even">
<td>Harina de pescado</td>
<td>9.6</td>
<td>10.8</td>
</tr>
</tbody>
</table>
<p>¹información generada en el laboratorio de Nutrición Animal, por estudiantes de la asignatura de Nutrición Animal Básica. ²Sauvant et al., 2002</p>
<p>En las materias primas presentadas en la tabla 9, se observan dos grupos de materias primas, el primer grupo (queso blando, pastel de carne y leche entera), con diferencias marcadas entre los valores sin y con hidrólisis, lo que podría indicarnos, un alto contenido de grasas ligadas a proteínas en estas; y un segundo grupo (harina de pescado y pastel de hígado) con diferencias menos marcadas, lo que podría indicar bajo contenido en grasa ligadas.</p>
<hr>
<p>De igual manera se presentan excepciones y materias primas de origen vegetal, también pueden presentar en su composición grasas ligadas, como por ejemplo el coco.</p>
<p>El contenido de extracto etéreo no es información suficiente, para determinar la calidad de una materia prima, para esto se debe realizar análisis más específicos como, por ejemplo: un perfil de ácidos grasos, en el que se pueda observar los contenidos de ácidos grasos saturados e insaturados, análisis que puede realizarse por cromatografía de gases. En la tabla 10 se presentan los perfiles de Ácidos grasos de varios aceites y grasas.</p>
<p>Tabla 10. Perfil de algunos ácidos grasos de algunos aceites y grasas de consumo humano.</p>
<p><img src="img/tabla_10.png" class="img-fluid"></p>
<hr>
<p><strong>Determinación de Nitrógeno y Proteína Cruda o Bruta</strong></p>
<p>En un análisis elemental de un alimento, lo más frecuente y menos complejo es investigar la proteína bruta de los diferentes alimentos o proteínas específicas.</p>
<p>No obstante, los procedimientos más utilizados no determinan directamente esta proteína, sino el contenido en <strong>nitrógeno</strong>, que se expresa como nitrógeno total. Las grasas, ni los carbohidratos, tienen en sus moléculas N, este, está presente solo en las proteínas, es por esta razón que para la determinación de Proteína Cruda se mide primero la cantidad de N.</p>
<p><strong>Método de Análisis:</strong></p>
<p>El N, que se obtiene mediante una combustión líquida en la que, en un primer paso, el nitrógeno de la muestra se convierte en sulfato amónico, el cual luego se transforma en amoniaco. Este amoniaco se destila y se valora en una solución ácido normalizada (anexo 4)</p>
<p>Esta técnica desarrollada por Kjeldahl, se ha convertido en método de referencia con múltiples modificaciones. Determina la materia nitrogenada total, que incluye tanto al nitrógeno proteico como al no proteico. Luego de medir el N total de la muestra, se convierte este resultado a un valor total de proteína cruda, mediante una multiplicación por el factor empírico 6.25 (este factor de conversión se basa en la suposición de que la proteína promedio, contiene alrededor de 16% de nitrógeno por unidad de peso, aun cuando en la práctica es posible una variación entre 12 y 19% de nitrógeno entre proteínas individuales). Por ejemplo, en la tabla 11, se muestra el rango de factores de conversión de proteína usados para convertir valores de nitrógeno a proteína cruda en diferentes materiales. De manera general, se observa que las materias primas de origen animal tienen factores de conversión más altos, lo que indica que el contenido e Nitrógeno en la proteína en estos alimentos es más bajo, que en las de origen vegetal.</p>
<p>Milton y Dintzis, 1981, en un trabajo de investigación con especies vegetales tropicales, encontraron que el factor de conversión más apropiado para estos, era 5.3, es decir que el contenido promedio de Nitrógeno en la proteína de estas especies, era de 19%.</p>
<p>Es importante remarcar que, a pesar las investigaciones tendientes a determinar el contenido de Nitrógeno de las especies vegetales forrajeras, como el mencionado anteriormente, el factor de conversión que se sigue utilizando a nivel mundial es el factor 6.25 para los forrajes.</p>
<p>La determinación de un factor de conversión propio para los forrajes, no es sencillo, debido al grado de heterogeneidad de los forrajes.</p>
<p>Con el método de Kjendhal, de determinación de proteína cruda, no se puede determinar la calidad de una proteína de una materia prima o alimento, para esto es necesario realizar un perfil de Aminoácidos - AA, que nos indica que tipo y contenidos de AA están haciendo parte de esa proteína, es decir se puede en qué proporción o porcentaje están los AA esenciales y los AA no Esenciales.</p>
<p>En los forrajes los contenidos de proteína son variables, dependiendo de la familia botánica a la que estos pertenezcan, en general las gramíneas poseen contenidos de proteína bajos,</p>
<hr>
<p>entre 7 – 12%, comparadas con las leguminosas que se encuentran entre 17 – 25% aproximadamente. Tabla 12.</p>
<p>Tabla 11. Factores de conversión de proteína usados para convertir nitrógeno a proteína, entre diferentes ingredientes alimenticios 1.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Ingredientes</th>
<th>Factor de conversión</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>CEREALES</strong></td>
<td></td>
</tr>
<tr class="even">
<td>Harina, harina integral de trigo</td>
<td>5.83</td>
</tr>
<tr class="odd">
<td>Harina, extracción media o baja de trigo</td>
<td>5.70</td>
</tr>
<tr class="even">
<td>Macarrones, espagueti, pastas de trigo</td>
<td>5.70</td>
</tr>
<tr class="odd">
<td>Salvado</td>
<td>6.31</td>
</tr>
<tr class="even">
<td>Arroz</td>
<td>5.95</td>
</tr>
<tr class="odd">
<td>Centeno, cebada y avena</td>
<td>5.83</td>
</tr>
<tr class="even">
<td><strong>LEGUMINOSAS, NUECES Y SEMILLAS</strong></td>
<td></td>
</tr>
<tr class="odd">
<td>Cacahuate</td>
<td>5.46</td>
</tr>
<tr class="even">
<td>Soya, semillas, harina o productos</td>
<td>5.71</td>
</tr>
<tr class="odd">
<td><strong>NUECES</strong></td>
<td></td>
</tr>
<tr class="even">
<td>Almendra</td>
<td>5.18</td>
</tr>
<tr class="odd">
<td>Nuez de Brasil</td>
<td>5.46</td>
</tr>
<tr class="even">
<td>Coco (sin corteza), castaña y otras nueces</td>
<td>5.30</td>
</tr>
<tr class="odd">
<td><strong>SEMILLAS</strong></td>
<td></td>
</tr>
<tr class="even">
<td>Ajonjolí, cártamo, girasol</td>
<td>5.30</td>
</tr>
<tr class="odd">
<td><strong>LECHE Y QUESO</strong></td>
<td></td>
</tr>
<tr class="even">
<td>Leche, todo tipo, fresca o seca</td>
<td>6.38</td>
</tr>
<tr class="odd">
<td><strong>ACEITE Y GRASAS</strong></td>
<td></td>
</tr>
<tr class="even">
<td>Margarina y Mantequilla</td>
<td>6.38</td>
</tr>
<tr class="odd">
<td><strong>OTROS ALIMENTOS</strong> 2</td>
<td>6.25</td>
</tr>
<tr class="even">
<td>Clara de Huevo³</td>
<td>6.70</td>
</tr>
<tr class="odd">
<td>Yema de Huevo³</td>
<td>6.62</td>
</tr>
<tr class="even">
<td>Huevo Entero³</td>
<td>6.68</td>
</tr>
</tbody>
</table>
<p>1 Fuente: MAFF (1975)</p>
<p>2 Incluye todas las carnes y pescados.</p>
<p>3 https://riunet.upv.es/bitstream/handle/…/Determinación%20de%20proteinas</p>
<hr>
<p>En la tabla 12, se presentan los contenidos de proteína cruda de algunas materias primas.</p>
<p>Tabla 12. Contenidos de proteína cruda de materias primas.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Alimento</th>
<th>% Proteína Cruda</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Leucaena</td>
<td>28.7</td>
</tr>
<tr class="even">
<td>Guinea</td>
<td>11.2</td>
</tr>
<tr class="odd">
<td><em>Brachiaria Decumbens</em></td>
<td>6.6</td>
</tr>
<tr class="even">
<td>Puntero</td>
<td>9.9</td>
</tr>
<tr class="odd">
<td>Pasto Kikuyo</td>
<td>19.3</td>
</tr>
<tr class="even">
<td>Semillas de Girasol</td>
<td>16.0</td>
</tr>
<tr class="odd">
<td>Maíz amarillo (grano)</td>
<td>10.4</td>
</tr>
<tr class="even">
<td>Torta de Soya</td>
<td>45.3</td>
</tr>
<tr class="odd">
<td>Harina de Pescado</td>
<td>65.3</td>
</tr>
</tbody>
</table>
<p>Información generada en el laboratorio de Nutrición Animal, por estudiantes de la asignatura de Nutrición Animal Básica. ² Sauvant et al., 2002</p>
<p>Los contenidos de proteína de las tortas, que son un subproducto de la extracción de aceite de los granos de oleaginosas, presentan contenidos de proteína altos (40-50%), con algunas excepciones como la torta de palmiste, que tiene un contenido de aproximadamente 15% de proteína cruda.</p>
<p>Las materias primas de origen animal utilizadas en las dietas para animales, se caracterizan por sus altos contenidos de proteína, por ejemplo, la Harina de pescado 65%, la harina de carne y huesos entre 40-60%, harina de sangre 85.8%.</p>
<p>Los contenidos de proteína cruda de los forrajes son variables. Un mismo forraje puede tener diferentes contenidos de proteína de acuerdo a la edad de este. En la tabla 13, se observa como el contenido de proteína del botón de oro disminuye con la edad.</p>
<p>Tabla 13. Contenido de proteína cruda de <em>Tithonia diversifolia</em> a diferentes edades de corte.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 19%">
<col style="width: 46%">
</colgroup>
<thead>
<tr class="header">
<th>Forraje</th>
<th>Días de corte</th>
<th>Contenido de Proteína Cruda (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>Tithonia diversifolia</em></td>
<td>30</td>
<td>23.4</td>
</tr>
<tr class="even">
<td></td>
<td>60</td>
<td>14.3</td>
</tr>
<tr class="odd">
<td></td>
<td>90</td>
<td>11.5</td>
</tr>
</tbody>
</table>
<p>García, 2004</p>
<p>En la mayoría de las gramíneas y otros forrajes verdes únicamente una parte del nitrógeno procede de las proteínas, mientras que el resto son sales inorgánicas de nitrógeno, nitrógeno amino, amidas, etc. Esto, sin embargo, no tiene importancia para un rumiante, ya que puede utilizar tanto el nitrógeno inorgánico (No Proteico -NNP) como el nitrógeno proteico - NP,</p>
<p>mediante la actividad microbiana del rumen, donde las bacterias medran en el nitrógeno no proteico y lo incorporan en sus propias proteínas.</p>
<p>El NNP se diluye en el rumen, convirtiéndose en la fuente nitrogenada más rápidamente disponible para la población microbiana. Jarrige, 1980.</p>
<p>El NNP en los forrajes esta entre 15-25% del N total, esta proporción es más elevada en los tallos que en las hojas e igualmente más elevada en leguminosas que en gramíneas (Jarrige, 1980). Chipatecua, Pabón, Cárdenas y Carulla, 2007, encontraron que el NNP del pasto Kikuyo, <em>Pennisetum clandestinum</em> era 19.6% del N total y en el <em>Lotus uliginosus</em> era de 32.8%</p>
<p>Todo el N de las proteínas de origen animal es N Proteico. (Tabla 14). Estas materias primas se caracterizan por tener buena cantidad de Aminoácidos Esenciales.</p>
<p>Tabla 14. Composición en proteína Cruda y Aminoácidos (g/kg MS) en productos de origen animal</p>
<table class="caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 16%">
<col style="width: 8%">
<col style="width: 22%">
<col style="width: 12%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>Alimentos¹</th>
<th>Proteína Cruda</th>
<th>Lisina</th>
<th>Metionina + Cistina</th>
<th>Triptófano</th>
<th>Treonina</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Harina de Pescado Graso 65</td>
<td>662</td>
<td>50.3</td>
<td>25.2</td>
<td>7</td>
<td>28.8</td>
</tr>
<tr class="even">
<td>Harina de Pescado Magro 65</td>
<td>646</td>
<td>50.4</td>
<td>23.9</td>
<td>6.5</td>
<td>27.3</td>
</tr>
<tr class="odd">
<td>Harina de Carne Grasa 55</td>
<td>538</td>
<td>28.2</td>
<td>12.4</td>
<td>2.8</td>
<td>17.3</td>
</tr>
<tr class="even">
<td>Harina de Carne Magra 55</td>
<td>561</td>
<td>29.5</td>
<td>12.9</td>
<td>2.9</td>
<td>18</td>
</tr>
<tr class="odd">
<td>Leche descremada Seca</td>
<td>349</td>
<td>28.1</td>
<td>12.5</td>
<td>4.4</td>
<td>15.3</td>
</tr>
<tr class="even">
<td>Suero de Leche descremado</td>
<td>128</td>
<td>11.3</td>
<td>5.3</td>
<td>2</td>
<td>5.3</td>
</tr>
</tbody>
</table>
<ol type="1">
<li>Gadoud <em>et al.</em>, 1992.</li>
</ol>
<p><strong>Fibra (Pared Celular) en los alimentos para consumo animal</strong></p>
<p>La fibra está constituida por celulosa, lignina, hemicelulosa, pectina, inulina, agar, quitina, gomas y silicatos; inclusive algunos autores incluyen como parte de la fibra algunos compuestos fenólicos, el ácido fítico y otros compuestos antinutricionales presentes en muy pequeñas cantidades en los alimentos.</p>
<p>A la celulosa y a la hemicelulosa les corresponden los mayores porcentajes en la constitución de la fibra, las siguen la lignina y las pectinas que poseen en algunos alimentos porcentajes relativamente altos. El resto de los componentes no tienen especial importancia nutricional y no representan cuantitativamente cifras elevadas.</p>
<p>La lignina es completamente indigerible tanto para monogástricos como para rumiantes, y su determinación sirve para predecir la digestibilidad en materia seca y energía de un alimento, porque se encuentra envolviendo a la celulosa y hemicelulosa y restringe al acceso a estos carbohidratos, que sí pueden ser digeribles.</p>
<p><strong><em>Métodos de Análisis</em>:</strong></p>
<p>Aunque Existen diferentes técnicas de análisis para la determinación del contenido de fibra (pared celular) de los alimentos en nutrición animal, se realizan principalmente análisis de</p>
<p>1Nutrición Animal Básica. Profesora <em>Luz Stella Muñoz Arboleda</em>. Departamento de Ciencia Animal</p>
<hr>
<p>Fibra Cruda-FC y Análisis de Van Soest (FDN-NDF-Fibra Detergente Neutra; FDA-ADF- Fibra Detergente Ácida; LDA-ADL-Lignina Detergente Ácida.</p>
<p>El análisis de Fibra Cruda es el método más antiguo, todavía en uso (desde 1859), utiliza como reactivos: álcali - NaOH y ácido - H2SO4, que destruyen parte de la Pared Celular dando como resultado un valor más bajo del real. En los años 60, el programa de investigación de Peter Van Soest, en el Departamento de Agricultura de los Estados Unidos, el cual condujo al sistema detergente de análisis de alimentos. Van Soest logró convencer a la comunidad científica de remplazar el sistema Weende o de análisis proximal en el cual se determinaba la Fibra Cruda, por su sistema detergente, con el que se encontrarían resultados de la pared celular más exactos determinando la Fibra Detergente Neutra, es este análisis no se utiliza ni álcali, ni ácido, se utiliza una solución detergente neutra.</p>
<p>El análisis de Van Soest fue inicialmente propuesto sólo para forrajes, es decir para materias primas ricas en fibra y con contenidos de almidones y proteínas relativamente bajos. La diferencia de los valores de Pared Celular utilizando los dos métodos de análisis /FC y FDN) en forrajes es bastante alta como se observa en la tabla 15. (Anexo 5).</p>
<p>Tabla 15. Contenidos de fibra (FDN – Fibra Detergente Neutra y FC – Fibra Cruda) de forrajes utilizando dos técnicas de análisis</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>FORRAJES</th>
<th>FDN</th>
<th>FC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>%</td>
<td>%</td>
</tr>
<tr class="even">
<td>Trébol Joven</td>
<td>40</td>
<td>22</td>
</tr>
<tr class="odd">
<td>Ensilaje de Maíz</td>
<td>36</td>
<td>21</td>
</tr>
<tr class="even">
<td>Heno de Alfalfa</td>
<td>51</td>
<td>24</td>
</tr>
<tr class="odd">
<td>Heno de Gramínea</td>
<td>65</td>
<td>30</td>
</tr>
</tbody>
</table>
<p>Los valores más bajos de la pared celular determinados como Fibra Cruda, se deben como se mencionó anteriormente a una dilución de componentes de la pared celular con la utilización del hidróxido y el ácido en la determinación, que no ocurre en la determinación de Fibra Detergente Neutra con el uso de una solución detergente neutra, donde los componentes de la Pared Celular no son diluidos.</p>
<p>Al análisis de Van Soest se le fueron realizando ajustes, para que de igual manera se pudiera aplicar a materias primas no forrajeras con altos contenidos de almidones o proteínas, los ajustes consistieron en adicionar enzimas como amilasas y proteasas a las muestras con altos contenidos en estos componentes.</p>
<p>El valor de Fibra Cruda es utilizado como referente en la alimentación de cerdos y aves, pero no en rumiantes, para los cuales se trabaja con contenidos de FDN del análisis de Van Soest.</p>
<p>Desde mucho tiempo atrás se acepta que al formular dietas para especies monogástricas se debe considerar un nivel máximo de fibra (5 y 10% de FC en aves y cerdos, respectivamente);</p>
<p>1Nutrición Animal Básica. Profesora <em>Luz Stella Muñoz Arboleda</em>. Departamento de Ciencia Animal</p>
<hr>
<p>lo contrario sucede en caso de formulación de dietas para rumiantes donde se debe considerar un nivel mínimo de fibra (25-30% de FDN). Lógicamente, la diferencia se debe a la fisiología digestiva propia de cada especie, cuando estos niveles no son tenidos en cuenta, se ocasionan trastornos digestivos y metabólicos en el animal.</p>
<p>En el caso de monogástricos, la digestión de los alimentos se realiza principalmente por acción enzimática. Sin embargo, en el caso de monogástricos herbívoros, el proceso de aprovechamiento de los alimentos se complementa con un proceso de fermentación. En ello, podemos citar como ejemplos al conejo, al caballo o al cuy. Estos animales si pueden utilizar la fibra a través del proceso de fermentación en el ciego, en el cual los principales productos de su fermentación son los ácidos grasos volátiles-AGV, que son fuente de energía para el organismo.</p>
<p>En cerdos y aves, el aprovechamiento de los nutrientes de los alimentos depende mayormente de la actividad enzimática que ocurre dentro del tracto digestivo del animal, con muy poca actividad fermentativa. Si se toma en cuenta una fórmula alimenticia para cerdos, se puede observar que aproximadamente el 80 por ciento de la dieta está conformado por dos ingredientes de origen vegetal (maíz y torta de soya), ambos con características particulares (el maíz como fuente energía y la torta de soya como fuente de proteína).</p>
<p>En la tabla 16 se presentan valores tanto de FC como de FDN-NDF de materias primas utilizadas en alimentación animal, donde se observa contenidos de Fibra en los forrajes más altos que en el resto de materias primas de origen vegetal.</p>
<p>Tabla 16. Contenidos de Pared Celular (FDN), Fibra Detergente Acida (FDA) y Lignina (LDA)¹</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Alimentos</th>
<th>FDN (%)</th>
<th>FDA (%)</th>
<th>LDA (%)</th>
<th>FC (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Leucaena</td>
<td>36.0</td>
<td>21.9</td>
<td>7.5</td>
<td></td>
</tr>
<tr class="even">
<td>Guinea</td>
<td>54.9</td>
<td>31.3</td>
<td>1.7</td>
<td></td>
</tr>
<tr class="odd">
<td>Brachiaria decumbens</td>
<td>55.6</td>
<td>29.4</td>
<td>3.2</td>
<td></td>
</tr>
<tr class="even">
<td>Puntero</td>
<td>74.9</td>
<td>48.1</td>
<td>11.2</td>
<td></td>
</tr>
<tr class="odd">
<td>Pasto Kikuyo</td>
<td>62.7</td>
<td>25.6</td>
<td>4.5</td>
<td></td>
</tr>
<tr class="even">
<td>Semillas de Girasol</td>
<td>28.8</td>
<td>18.7</td>
<td>5.7</td>
<td>15,5</td>
</tr>
<tr class="odd">
<td>Maíz amarillo (grano)</td>
<td>10.4</td>
<td>2.6</td>
<td>2.5</td>
<td>2,2</td>
</tr>
<tr class="even">
<td>Torta de Soya²</td>
<td>12.4</td>
<td>7.4</td>
<td>0.4</td>
<td>6,1</td>
</tr>
<tr class="odd">
<td>Harina de pescado²</td>
<td>0.0</td>
<td>0.0</td>
<td>0.0</td>
<td></td>
</tr>
</tbody>
</table>
<p>Información generada en el laboratorio de Nutrición Animal, por estudiantes de la asignatura de Nutrición Animal Básica. ² Sauvant <em>et al.</em>, 2002</p>
<p>Los valores de FC y FDA de las semillas de girasol, maíz amarillo y torta de soya son similares, pues en ambos se pierde hemicelulosa, es decir parte de la pared celular. La Harina de pescado por ser materia prima de origen animal, al no tener en su estructura pared celular, su contenido de fibra es cero (0.0)</p>
<p>1Nutrición Animal Básica. Profesora <em>Luz Stella Muñoz Arboleda</em>. Departamento de Ciencia Animal</p>
<hr>
<p>Una de las maneras de evaluar la calidad de los forrajes es a través del Valor Relativo. El <em>Valor Relativo de los Forrajes</em> combina los factores nutricionales más importantes (el potencial de consumo y la digestibilidad).</p>
<p>La calidad de los forrajes es la pieza fundamental de la formulación de raciones en rebaños de alta producción. Según lo explicado anteriormente, los forrajes constituyen el factor limitante de la producción animal en cuanto que aportan la mayor parte de la FDN (que limita el consumo) y FDA (que determina el valor energético de la ración). Con frecuencia hemos considerado la proteína de los forrajes como criterio de valoración de su calidad, pero no es así. Sin embargo, cuando la ingestión o la digestibilidad de la ración se ve comprometida como consecuencia de la calidad del forraje, no hay solución. Debemos redefinir el concepto de calidad de forrajes para la alimentación de los rumiantes, de tal manera que éste dependa de su capacidad de estimular la máxima producción, lo que a su vez depende de la capacidad de consumo (FDN) y de su digestibilidad (FDA). Esta estrategia de valoración de forrajes ha estimulado a investigadores de la Universidad de Minnesota (Linn y Martin, 1989, citados por Calsamiglia, 1997) a desarrollar el índice de calidad de forrajes: el <em>Valor Relativo de Forrajes (VRF)</em>.</p>
<p>El potencial de consumo está afectado con el contenido de FDN, según la siguiente formula: Consumo de MS como % PV = 120/%FDN</p>
<p>La digestibilidad de la MS – DMS se calcula en función del contenido de FDA: DMS (%) = 88,9 - (0,779 x %FAD)</p>
<p>El valor relativo de los forrajes (exceptuando el ensilado de maíz) se calcula como:</p>
<p>VRF = (DMS x Consumo MS)/1,29</p>
<p>Este valor es un índice y no tiene unidades, pero permite comparar la calidad (entendida como la capacidad de un forraje de producir una respuesta productiva mayor) de leguminosas, gramíneas y sus mezclas, bien sean en fresco, ensiladas o henificadas. Este sistema de valoración ha sido adoptado oficialmente por el American Forage and Grassland Council como criterio de valoración de la calidad de los forrajes. La tabla 17 muestra la clasificación por calidad de estos forrajes.</p>
<p>Tabla 17. Clasificación de Gramineas y Leguminosas y sus mezclas. Calsamiglia 1997</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Clasificación</th>
<th>FDN</th>
<th>FDA</th>
<th>VRF</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>% Materia Seca</td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Excelente</td>
<td>&lt; 41</td>
<td>&lt; 31</td>
<td>&gt; 151</td>
</tr>
<tr class="odd">
<td>Primera</td>
<td>40-46</td>
<td>31-35</td>
<td>151-125</td>
</tr>
<tr class="even">
<td>Segunda</td>
<td>47-53</td>
<td>36-40</td>
<td>124-103</td>
</tr>
<tr class="odd">
<td>Tercera</td>
<td>54-60</td>
<td>41-42</td>
<td>102-87</td>
</tr>
<tr class="even">
<td>Cuarta</td>
<td>61-62</td>
<td>43-45</td>
<td>86-75</td>
</tr>
<tr class="odd">
<td>Quinta</td>
<td>&gt; 65</td>
<td>&gt; 45</td>
<td>&lt; 75</td>
</tr>
</tbody>
</table>
<p>1Nutrición Animal Básica. Profesora <em>Luz Stella Muñoz Arboleda</em>. Departamento de Ciencia Animal</p>
<hr>
<p>Si se analiza en detalle el nivel de producción, la capacidad de consumo y los límites de fibra recomendados en la dieta, se puede concluir que la calidad del forraje (valorado en función del consumo y de la digestibilidad) es el factor limitante de la producción, y que, en vacunos de producción media-alta, es necesaria la utilización de forrajes con un VRF superior a 125. Sería interesante que productores, ganaderos y profesionales del sector lechero adoptaran este nuevo sistema de valoración de forrajes.</p>
<p>En la tabla 18 a manera de ejemplo se presenta la evaluación de dos forrajes con el de <em>Valor Relativo Forrajero</em></p>
<p>Tabla 18. Evaluación de morera <em>Morus alba</em> y <em>Cratylia argentea</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 23%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 19%">
<col style="width: 8%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th>Forraje</th>
<th>Proteína Cruda (%)</th>
<th>FDN (%)</th>
<th>FDA (%)</th>
<th>Consumo MS % PV</th>
<th>DMS %</th>
<th>VRF</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>Morus alba</em></td>
<td>24,4</td>
<td>29,8</td>
<td>18,8</td>
<td>4,0</td>
<td>74,3</td>
<td>231</td>
</tr>
<tr class="even">
<td><em>Cratylia argentea</em></td>
<td>23,8</td>
<td>60,1</td>
<td>34,1</td>
<td>2,0</td>
<td>62,3</td>
<td>96</td>
</tr>
</tbody>
</table>
<p>Consumo de MS como % PV = 120/%FDN; DMS (%) = 88,9 - (0,779 x %FAD) VRF = (DMS x Consumo MS)/1,29</p>
<p>Según el índice del VRF, la morera de este ejemplo se clasificaría como forraje de Excelente calidad y el de cratilia como de tercera.</p>
<p>De igual manera, es necesario remarcar que un mismo forraje puede tener varias clasificaciones, dependiendo del lugar de procedencia (suelos, m.s.n.m. etc), estructura de la planta analizada (tallos, hojas, planta completa), edad de corte (30, 60, 90 días) o estado de desarrollo (prefloración, floración y fructificación). En la tabla 19, se presenta el forraje Ray- grass, clasificado de diferentes maneras, según la composición química:</p>
<p>Tabla 19. Clasificación según Calsamiglia 1997, de diferentes muestras del forraje <em>Lolium perenne</em> Ray-grass</p>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>MS</th>
<th>Humedad</th>
<th>Cenizas</th>
<th>PC</th>
<th>EE</th>
<th>FB</th>
<th>FDN</th>
<th>FDA</th>
<th>LDA</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(%)</td>
<td>(%)</td>
<td>(% MS)</td>
<td>(%MS)</td>
<td>(%MS)</td>
<td>(%MS)</td>
<td>(%MS)</td>
<td>(%MS)</td>
<td>(%MS)</td>
</tr>
<tr class="even">
<td>Ray-grass verde EXCELENTE</td>
<td>23,8</td>
<td>76,2</td>
<td>12,4</td>
<td>19,7</td>
<td>4,0</td>
<td>19,1</td>
<td>40,5</td>
<td>22,6</td>
</tr>
<tr class="odd">
<td>Ray-grass verde PRIMERA</td>
<td>23,3</td>
<td>76,7</td>
<td>12,8</td>
<td>14,4</td>
<td>3,2</td>
<td>23,3</td>
<td>46,0</td>
<td>27,8</td>
</tr>
<tr class="even">
<td>Ray-grass verde SEGUNDA</td>
<td>26,1</td>
<td>73,9</td>
<td>13,2</td>
<td>12,0</td>
<td>2,6</td>
<td>26,6</td>
<td>52,1</td>
<td>31,3</td>
</tr>
<tr class="odd">
<td>Ray-grass verde TERCERA</td>
<td>29,7</td>
<td>70,3</td>
<td>12,4</td>
<td>10,4</td>
<td>2,3</td>
<td>30,4</td>
<td>59,3</td>
<td>35,3</td>
</tr>
<tr class="even">
<td>Ray-grass verde CUARTA</td>
<td>30,8</td>
<td>69,2</td>
<td>14,4</td>
<td>8,0</td>
<td>2,3</td>
<td>32,3</td>
<td>65,2</td>
<td>38,0</td>
</tr>
</tbody>
</table>
<p><strong>Almidones y azucares</strong></p>
<p>Para su determinación existen protocolos de laboratorio del almidón total, azucares totales y reductores, igualmente para la estimación del contenido de almidones y azucares de una materia prima se utiliza el propuesto por Henneberg y Stohmann (1867) en la estación experimental de Weende (Alemania), en el cual se estima con un a formula, estos componentes a partir de los analizados.</p>
<p>1Nutrición Animal Básica. Profesora <em>Luz Stella Muñoz Arboleda</em>. Departamento de Ciencia Animal</p>
<hr>
<p>A la estimación de los almidones y azúcares por el método de Weende se le llamó Contenido de Extracto Libre de Nitrógeno – ELN o Extracto No Nitrogenado.</p>
<p><span class="math display">\[
ELN = 100 - (\% \text{Cenizas} + \%PC + \%EE + \%FC)
\]</span></p>
<p>Como se explicó anteriormente, la FC no determina los componentes de la pared celular de manera exacta, ya que los reactivos utilizados en esta determinación diluyen parte de la pared celular. Por esta razón, algunos investigadores reemplazan FC por FDN en la fórmula con la finalidad de obtener un resultado más fiable de almidones y azúcares:</p>
<p><span class="math display">\[
ELN = 100 - (\% \text{Cenizas} + \%PC + \%EE + \%FDN)
\]</span></p>
<p>Si tomamos como ejemplo los contenidos de FC y FDN del heno de gramínea de la tabla 15 y tenemos en cuenta los otros valores de los nutrientes de este heno:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Componente</th>
<th>Porcentaje (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cenizas</td>
<td>10%</td>
</tr>
<tr class="even">
<td>PC</td>
<td>11%</td>
</tr>
<tr class="odd">
<td>EE</td>
<td>3%</td>
</tr>
<tr class="even">
<td><strong>FC</strong></td>
<td><strong>30%</strong></td>
</tr>
<tr class="odd">
<td><strong>FDN</strong></td>
<td><strong>60%</strong></td>
</tr>
</tbody>
</table>
<p>Al utilizar las dos fórmulas, para estimar el ELN:</p>
<ul>
<li>Usando FC:</li>
</ul>
<p><span class="math display">\[
FC = 100 - (10 + 11 + 3 + \mathbf{30}) = 46\% \text{ de ELN}
\]</span></p>
<ul>
<li>Usando FDN:</li>
</ul>
<p><span class="math display">\[
FDN = 100 - (10 + 11 + 3 + \mathbf{60}) = 16\% \text{ de ELN}
\]</span></p>
<p>Un heno de gramínea con 46% de almidones y azúcares no sería una buena estimación de los azúcares y almidones de un forraje, 16% sería una mejor estimación de estos componentes, aunque sigue siendo un poco alto.</p>
<section id="energía-bruta-eb" class="level2">
<h2 class="anchored" data-anchor-id="energía-bruta-eb">Energía Bruta (EB)</h2>
<p>La técnica consiste en quemar una muestra en una cámara en acero inoxidable (‘bomba’), rodeada por una cantidad precisa de agua y de medir el aumento de temperatura del agua (Anexo 6). Después de una calibración con muestras de referencia, se puede deducir la cantidad de energía (expresada en calorías o en joules) producida por la combustión de la muestra. El resultado corresponde a la cantidad de energía bruta presente en la muestra.</p>
<p>El contenido de Energía Bruta, es solo las calorías que se producen por la combustión de la muestra, no es un parámetro que indica el valor energético del alimento o materia prima. Para conocer cuántas calorías de las que están en los alimentos el animal puede utilizar se necesita conocer, por medio de la determinación de la digestibilidad (<em>in vitro</em> o <em>in vivo</em>) o estimación por ecuaciones de predicción los valores de Energía Digestible - ED.</p>
<p>En la tabla 20, se presentan valores de Energía Bruta y de Energía Digestible de diferentes materias primas.</p>
<p>Tabla 20. Energía Bruta y Digestible de Materias Primas</p>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th>Materia Prima</th>
<th>Energía Bruta (kcal/kg MS)</th>
<th>Energía Digestible¹ (kcal/kg MS)</th>
<th>Digestibilidad de la Energía (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Maíz</td>
<td>3860</td>
<td>3390</td>
<td>87</td>
</tr>
<tr class="even">
<td>Avena</td>
<td>4100</td>
<td>2630</td>
<td>64</td>
</tr>
<tr class="odd">
<td>Torta de Soya</td>
<td>4130</td>
<td>3520</td>
<td>85</td>
</tr>
<tr class="even">
<td>Heno de Gramínea</td>
<td>4222</td>
<td>2610</td>
<td>61</td>
</tr>
<tr class="odd">
<td>Paja de Trigo</td>
<td>4320</td>
<td>1800</td>
<td>41</td>
</tr>
</tbody>
</table>
<p>¹ En cerdos.</p>
<p>Como se mencionó anteriormente, la Energía Digestible son las calorías que el animal puede utilizar por cada kg de MS que consume del alimento, por ejemplo, en el caso del maíz:</p>
<ul>
<li><p>En 1 kg de MS que consumiría el animal hay 3860 kcal y el animal solo podría utilizar o serían digestibles 3390, es decir un 87% de las ingeridas.</p></li>
<li><p>En el caso de la paja de trigo, el animal solo podría utilizar 1800 kcal de las 4320 que hay en la paja de trigo, es decir un 41%.</p></li>
</ul>
</section>
<section id="referencias-bibliográficas" class="level2">
<h2 class="anchored" data-anchor-id="referencias-bibliográficas">Referencias Bibliográficas</h2>
<p>Calsamiglia S. 1997. Nuevas bases para la utilización de fibras en dietas de rumiantes. XIII Curso de especialización FEDNA</p>
<p>Chipatecua M, Pabón M, Quím, Cárdenas E y Carulla J. 2007. Efecto de la combinación de una leguminosa tanífera (Lotus uliginosus cv Maku) con Pennisetum clandestinum, sobre la degradación in vitro de proteína y materia seca. Revista Colombiana de Ciencias Pecuarias. Vol, 20 No.&nbsp;1.</p>
<p>Gadoud R., Joseph M-M., Jussiau R., Lisberney Mj., Mangeol B., Montmeas L., Tarrit A. 1992. Nutrition et Alimentation des animaux d´élevage. Editions Foucher. Paris. Francia</p>
<p>García Martínez, E. y Fernández Segovia, I. Determinación de proteínas de un alimento por el método Kjeldahl. Valoración con un ácido fuerte. ETSIAMN. Universitat Politècnica de València. https://riunet.upv.es/bitstream/handle/…/Determinación%20de%20proteinas.pdf</p>
<p>García L. 2004. Trabajo de Grado Zootecnia. Universidad Nacional de Colombia.</p>
<p>Hart F. L. 1991. Análisis moderno de los alimentos; Acribia. Zaragoza (España).</p>
<p>Jarrige R. 1980. Alimentation de Ruminants. INRA, Paris, 2 edition</p>
<p>Kirk R. S., Sawyer R; Egan, H. 1996. Composición y análisis de alimentos de Pearson, segunda edición; Compañía editorial continental SA de CV, México.</p>
<p>Leterme P. y Estrada F. 2010 Análisis de Alimentos y forrajes. Protocolos de Laboratorio. Departamento de Ciencia Animal. Universidad Nacional de Colombia. Palmira.</p>
<p>López Córdoba A. Análisis Instrumental II. Escuela MEH. https://analisisinstrumentalmeh.files.wordpress.com/…/analisis-de-aceites-.</p>
<p>MAFF (Ministry of Agriculture, Fisheries and Food), 1981 The analysis of agricultural materials, RB427, Second Edition, HMSO, London, 226 p.</p>
<p>Martínez, L.F. 2019. Dibujo del estudiante de Ingeniería Agronómica de la Universidad Nacional de Colombia, Sede Palmira.</p>
<p>Milton K. Y Dintzis F. 1981. Nitrogen to Protein conversion factors for tropical Plant samples. Biotropica, Vol, 13. Pp:177-181</p>
<p>Nutrición y alimentación de peces y camarones cultivados. Manual de capacitación. http://www.fao.org/docrep/field/003/ab492s/AB492S06.htm</p>
<p>Owen A. 2000. Notas de Clase de la asignatura Nutrición Animal Aplicada</p>
<p>Ruiz M., Leterme P. Y Muñoz L.S. Desarrollo de una metodología para evaluar los procesos fermentativos de forrajes a nivel del intestino grueso de cerdos. Acta Agronómica Vol 54 (4). 2005.</p>
<p>Sauvant D., Perez ,J.M., Tran G. 2002. Tables de composition et de valeur nutritive des matieres premieres destinées aux animaux d´élevage. Editions INRA. Paris. Francia.</p>
<p>Segura F., Echeverri R., Patiño A. y Mejía A. 2007. Descripción y discusión acerca de los métodos de análisis de fibra y del valor nutricional de forrajes y alimentos para animales. VITAE, Revista De La Facultad De Química Farmacéutica. Volumen 14 número 1. págs. 72-81</p>
<p>Técnicas de análisis físico – químico de alimentos - Analiza Calidad www.analizacalidad.com/docftp/fi1441ene2007.pdf</p>
<p>Van Soest, P.J. 1994. Nutritional ecology of the ruminant. 2nd Edition, Cornell University Press, Ithaca, 476.</p>
<p>ISO 15304 ”Animal and vegetable fats and oils – Determination of the content of trans fatty acid isomers of vegetable fats and oils – Gas chromatographic method.</p>
</section>
<section id="anexo-1.-determinación-del-contenido-en-materia-seca-mediante-calor" class="level2">
<h2 class="anchored" data-anchor-id="anexo-1.-determinación-del-contenido-en-materia-seca-mediante-calor">Anexo 1. Determinación del Contenido en Materia Seca mediante Calor</h2>
<p>Caso de un alimento húmedo (alto contenido de agua) (Ej. Forraje, frutas)</p>
<p>Para poder moler la muestra y analizarla, se debe desecar la muestra a una temperatura de 60°C para impedir que la desecación afecte su composición química. A esta determinación se le conoce como <strong>Materia Seca Inicial</strong>. Sin embargo, esta temperatura no permite una desecación completa de la muestra. Una vez la muestra desecada y molida, se debe determinar de nuevo su contenido en materia seca. Esta segunda determinación se llama <strong>Materia Seca Analítica</strong>. Se utiliza para expresar los resultados en base seca.</p>
<section id="material-necesario" class="level3">
<h3 class="anchored" data-anchor-id="material-necesario">Material necesario</h3>
<ul>
<li>El mismo material que para el análisis del alimento seco, más:</li>
<li>Balanza de precisión (0.01 g)</li>
<li>Recipientes en aluminio + marcador</li>
<li>Bolsas de papel o periódico o bandejas de aluminio</li>
</ul>
</section>
<section id="procedimiento-de-materia-seca-inicial---ms-inicial" class="level3">
<h3 class="anchored" data-anchor-id="procedimiento-de-materia-seca-inicial---ms-inicial">Procedimiento de <strong>Materia Seca Inicial - MS inicial</strong></h3>
<ol type="1">
<li>Tomar una muestra (100-300 g) homogénea y representativa de la materia fresca a analizar, colocarla en un recipiente en aluminio o periódico previamente tarado con la balanza de precisión.</li>
<li>Pesar el recipiente de aluminio o papel periódico (tara).</li>
<li>Poner la balanza en (0,0) con el periódico sobre esta</li>
<li>Pesar la muestra junto con el periódico.</li>
<li>Secar en estufa a 60°C por 24-48 h.</li>
<li>Dejar enfriar 30 min a temperatura ambiente.</li>
<li>Pesar nuevamente y calcular el %MS inicial. Después de este secado la muestra es molida.</li>
</ol>
<p>Ejemplo de cálculo del <strong>pasto BORE</strong> <em>Alocasia macrorrhiza</em></p>
<ul>
<li>Peso del periódico = Tara = 13.2g (2)</li>
<li>Peso del forraje fresco = 320.6g (4)</li>
<li>Peso seco después del secado = Tara + Peso seco = 90.8g (7)</li>
</ul>
<p><span class="math display">\[
\%MS_{\text{ inicial}} = \left( \frac{(\text{Tara} + \text{Peso seco}) - \text{Tara}}{\text{Peso fresco}} \right) \times 100
\]</span></p>
<p><span class="math display">\[
\%MS_{\text{ inicial}} = \left( \frac{(90.8g - 13.2g)}{320.6g} \right) \times 100 = \left( \frac{77.6g}{320.6g} \right) \times 100 = 24.2\%
\]</span></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/procedimiento_ms.jpg" class="img-fluid figure-img"></p>
<figcaption>Figura 1. Procedimiento para la Determinación de Materia Seca Inicial</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/fig2-molienda-forraje.jpg" class="img-fluid figure-img"></p>
<figcaption>Figura 2. Molienda del forraje a tamaño de partícula de 1 mm</figcaption>
</figure>
</div>
</section>
</section>
<section id="determinación-de-la-materia-seca-analítica" class="level2">
<h2 class="anchored" data-anchor-id="determinación-de-la-materia-seca-analítica">Determinación de la Materia Seca Analítica</h2>
<p>Después de la molienda, de la harina del forraje secada a 60°C (se acepta que la molienda no afecta el contenido en agua de manera significativa), se toma una pequeña muestra (± 3 g), no destinada al análisis. Se coloca a 105°C hasta peso constante (24 h), se determina el peso antes y después de la desecación y se calcula el porcentaje de materia seca. Este es un método GRAVIMÉTRICO. Con este método se calcula el contenido de materia seca analítica.</p>
<section id="material-necesario-1" class="level3">
<h3 class="anchored" data-anchor-id="material-necesario-1">Material necesario</h3>
<ul>
<li>Estufa ventilada (temperatura máxima &gt; 105°C)<br>
</li>
<li>Balanza analítica (precisión: 0.0001g)<br>
</li>
<li>Crisoles en porcelana (Ø 3-4 cm)<br>
</li>
<li>Desecador con Silica gel<br>
</li>
<li>Espátula, pinza, lapicero, formulario para toma de datos</li>
</ul>
</section>
<section id="preparación-de-los-crisoles" class="level3">
<h3 class="anchored" data-anchor-id="preparación-de-los-crisoles">Preparación de los crisoles</h3>
<ul>
<li>Desecar crisoles a 105°C durante 30 minutos<br>
</li>
<li>Colocarlos en un desecador durante 20-30 minutos</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/fig3-preparacion-crisoles.jpg" class="img-fluid figure-img"></p>
<figcaption>Figura 3. Preparación de los crisoles para la determinación de MS analítica</figcaption>
</figure>
</div>
</section>
<section id="procedimiento-de-ms-analítica" class="level3">
<h3 class="anchored" data-anchor-id="procedimiento-de-ms-analítica">Procedimiento de MS Analítica</h3>
<ol start="9" type="1">
<li>Se pesa un crisol en la balanza analítica</li>
<li>Se anota su número y su peso (T=tara).<br>
</li>
<li>Se coloca la balanza en 0.0 con el crisol</li>
<li>Se agrega la muestra del forraje molido de 3-5g con la espátula y se anota el peso. Se debe medir con precisión una cantidad cercana de 3g (Ej. 2.9962 o 3. 094)</li>
<li>Se colocan los crisoles con la muestra a 105°C entre 6 a 24 h.<br>
</li>
<li>Se sacan los crisoles con una pinza de la estufa y se colocan en un desecador entre 20-30 min.<br>
</li>
<li>Se pesan los crisoles con la muestra y se anota el peso final.<br>
</li>
<li>Se calcula el porcentaje de materia seca analítica.</li>
</ol>
<p>Ejemplo de cálculo del <strong>pasto BORE</strong> <em>Alocasia macrorrhiza</em></p>
<ul>
<li>Peso del crisol = Tara = 25.1508g (10)<br>
</li>
<li>Peso de la muestra en g, aproximadamente 3g = 3.2321g (12)<br>
</li>
<li>Peso del crisol + Materia Seca = 28.2311g (15)</li>
</ul>
<p><span class="math display">\[
\%MS_{\text{ analítica}} = \left( \frac{(\text{Peso del crisol} + \text{MS}) - \text{Peso del crisol}}{\text{Peso muestra }} \right) \times 100
\]</span></p>
<p><span class="math display">\[
\%MS_{\text{ analítica}} = \left( \frac{(28.2311g - 25.1508g)}{3.2321g} \right) \times 100 = \left( \frac{3.0803g}{3.2321g} \right) \times 100 = 95.3\%
\]</span></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/fig4-ms-analitica.jpg" class="img-fluid figure-img"></p>
<figcaption>Figura 4. Procedimiento para la determinación de Materia Seca Analítica</figcaption>
</figure>
</div>
</section>
</section>
<section id="estimación-de-materia-seca-total---mst" class="level2">
<h2 class="anchored" data-anchor-id="estimación-de-materia-seca-total---mst">Estimación de Materia Seca Total - MST</h2>
<p><span class="math display">\[
MST = \frac{\left(\% \text{ materia seca a } 60\,^{\circ}C\right) \times \left(\% \text{ materia seca a } 105\,^{\circ}C\right)}{100}
\]</span></p>
<p>Ejemplo:</p>
<p><span class="math display">\[
MST = \frac{(24.2\% \times 95.3\%)}{100} = 23.7\%
\]</span></p>
</section>
<section id="anexo-2.-determinación-de-cenizas" class="level2">
<h2 class="anchored" data-anchor-id="anexo-2.-determinación-de-cenizas">Anexo 2. Determinación de Cenizas</h2>
<p>Las cenizas representan la porción mineral, es decir inorgánica, del alimento. Es la parte que queda después de la eliminación del agua y de los componentes orgánicos por combustión, aunque parte de las cenizas sean de origen orgánico (S y P provenientes de proteínas). Además, parte de algunos minerales se pierden por volatilización (Na, Cl, K, P, S). Es también un método GRAVIMÉTRICO.</p>
<p>Lo ideal es realizar la determinación directamente después de la determinación del contenido en materia seca ya que se necesita también desecar las muestras en crisoles de porcelana antes de quemarlas en la mufla.</p>
<p>Cuando un alimento ha sido contaminado por tierra, como es el caso de las raíces (yuca) o de forrajes (heno), las cenizas presentes en la muestra incluyen las de la tierra. Las cenizas que vienen solamente del alimento son solubles en ácido clorhídrico 1 N, al contrario de la sílice. Entonces, se va a determinar esta fracción para conocer las cenizas de origen alimenticio.</p>
</section>
<section id="cenizas-totales" class="level2">
<h2 class="anchored" data-anchor-id="cenizas-totales">Cenizas Totales</h2>
<section id="material-necesario-2" class="level3">
<h3 class="anchored" data-anchor-id="material-necesario-2">Material necesario</h3>
<ul>
<li>Mufla (hasta 600 °C)<br>
</li>
<li>Balanza analítica<br>
</li>
<li>Desecador<br>
</li>
<li>Crisoles en porcelana<br>
</li>
<li>Formulario, lapicero<br>
</li>
<li>Estufa ventilada</li>
</ul>
</section>
<section id="procedimiento" class="level3">
<h3 class="anchored" data-anchor-id="procedimiento">Procedimiento</h3>
<ol type="1">
<li>Desecar crisoles a 105°C durante 30 minutos y colocarlos en un desecador durante 20-30 minutos.<br>
</li>
<li>Pesar un crisol, anotar su número y su peso (T = tara) = Peso Crisol.<br>
</li>
<li>Tarar la balanza, es decir colocarla en (0.0)</li>
<li>Colocar ± 3 a 5g de muestra en el crisol con una espátula y anotar el peso (Peso de Muestra)</li>
<li>Colocar los crisoles con la muestra en una mufla a 550-600°C durante un mínimo de 6 h. Apagar la mufla, abrir la puerta y esperar 10 minutos</li>
<li>Colocar los crisoles con una pinza en un desecador. Dejar el grifo abierto 2 minutos. Dejar enfriar durante al menos 1 h</li>
<li>Pesar los crisoles y anotar el peso (T + Cenizas) = Peso Crisol + Cenizas</li>
</ol>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/fig5-preparacion-crisoles-cenizas.jpg" class="img-fluid figure-img"></p>
<figcaption>Figura 5. Preparación de los crisoles para la determinación de cenizas. Estufa analítica 30 min y desecador 20-30 min</figcaption>
</figure>
</div>
<p>Ejemplo de cálculo del <strong>pasto BORE</strong> <em>Alocasia macrorrhiza</em></p>
<p><span class="math display">\[
\% \text{ Cenizas} = \frac{\left( \text{Peso del crisol} + \text{Cenizas} \right) - \text{Peso del crisol}}{\text{Peso muestra} \times MS_{\text{ analítica}}} \times 100
\]</span></p>
<p>Ejemplo de cálculo:</p>
<p><span class="math display">\[
\% \text{ Cenizas} = \frac{(25.8707g - 25.4508g)}{(3.2156g \times 0.9503g)} \times 100 = 13.7\%
\]</span></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/fig6-determinacion-cenizas.jpg" class="img-fluid figure-img"></p>
<figcaption>Figura 6. Determinación de cenizas.</figcaption>
</figure>
</div>
</section>
</section>
<section id="cenizas-insolubles-en-hcl-1n-sílice" class="level2">
<h2 class="anchored" data-anchor-id="cenizas-insolubles-en-hcl-1n-sílice">Cenizas Insolubles en HCl 1N (Sílice)</h2>
<p>El principio es solubilizar las cenizas de origen alimenticio en HCl 1N, filtrar la parte insoluble, quemar el filtro y pesar la fracción insoluble.</p>
<section id="material-necesario-3" class="level3">
<h3 class="anchored" data-anchor-id="material-necesario-3">Material necesario</h3>
<ul>
<li>Mufla<br>
</li>
<li>Balanza analítica<br>
</li>
<li>Desecador<br>
</li>
<li>Beaker de 125 ml + vidrio de reloj<br>
</li>
<li>Crisoles filtrantes en vidrio (tipo P3 o P4), tarados a 105°C<br>
</li>
<li>Solución de HCl 1N<br>
</li>
<li>Bomba de vacío<br>
</li>
<li>Estufa con ventilación</li>
</ul>
</section>
<section id="procedimiento-1" class="level3">
<h3 class="anchored" data-anchor-id="procedimiento-1">Procedimiento</h3>
<ol type="1">
<li>Después de la pesada de los crisoles provenientes de la mufla, agregar a las cenizas un exceso de solución de HCl 1N.<br>
</li>
<li>Trasladar en un beaker y hervir 2 minutos con un vidrio de reloj sobre el beaker.<br>
</li>
<li>Filtrar sobre el crisol filtrante previamente tarado, limpiar varias veces con agua destilada</li>
<li>Quemar a 550 °C durante 3 h</li>
<li>Colocar al menos 1 h en un desecador</li>
<li>Pesar el crisol (T + Sílice) y calcular el contenido en sílice y, por diferencia, el de cenizas solubles.</li>
</ol>
</section>
</section>
<section id="anexo-3.-determinación-de-extracto-etéreo" class="level2">
<h2 class="anchored" data-anchor-id="anexo-3.-determinación-de-extracto-etéreo">Anexo 3. Determinación de Extracto Etéreo</h2>
<p>Su determinación se basa en la propiedad de los lípidos de ser solubles en disolventes orgánicos apolares como el éter de petróleo. El análisis de determinación de las grasas se realiza mediante un método GRAVIMÉTRICO que consiste en el aislamiento de la grasa por dilución en el disolvente. El último es eliminado por evaporación. Se extraen también otros componentes solubles en disolventes apolares como los fosfolípidos, los esteroles, los pigmentos, algunas vitaminas, etc. Sin embargo, la grasa representa generalmente 99% de la materia soluble, de tal manera que se puede considerar que el EXTRACTO ETÉREO (EE) es un muy buen estimativo de la cantidad total de grasa presente en un alimento.</p>
<p>Para extraer la grasa en continuo, se utiliza un aparato en vidrio llamado equipo de Soxhlet (Figura 7). En este caso, el extracto se realiza en frío. Se puede también trabajar con equipos especiales que permiten trabajar con disolvente caliente (Ej: Buchï).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/fig7-metodo-soxhlet.jpg" class="img-fluid figure-img"></p>
<figcaption>Figura 7. Extracción en continuo de la grasa: método de soxhlet</figcaption>
</figure>
</div>
<p>El aparato de Soxhlet se compone de tres partes en vidrio (Figura 8):</p>
<ul>
<li>1 balón de 125 a 250 ml</li>
<li>1 extractor Soxhlet compuesto de una cámara y un sifón</li>
<li>1 refrigerante</li>
</ul>
<p>Se coloca el éter de petróleo en el balón, y el dedal con la muestra a analizar en el extractor Soxhlet. Se calienta el balón hasta obtener la ebullición del éter. Este último, en forma de gas, pasa por el sifón, alcanza el refrigerante, se condensa y se acumula en la cámara con la muestra. Cuando el nivel del éter, cargado de grasa, llega a la cima del sifón, regresa al balón, donde se evapora de nuevo, pero la grasa va quedando en el balón. La extracción continua toma ± 4-6 h.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/fig8-partes-extractor-soxhlet.jpg" class="img-fluid figure-img"></p>
<figcaption>Figura 8. Partes de Vidrio del Extractor Soxhlet</figcaption>
</figure>
</div>
</section>
<section id="extracción-de-la-grasa-libre" class="level2">
<h2 class="anchored" data-anchor-id="extracción-de-la-grasa-libre">Extracción de la grasa libre</h2>
<p>Procedimiento para la determinación de Extracto Etéreo (Figuras 9 y 10)</p>
<section id="material-necesario-4" class="level3">
<h3 class="anchored" data-anchor-id="material-necesario-4">Material necesario</h3>
<ul>
<li>Aparatos de Soxhlet<br>
</li>
<li>Placas de calefacción<br>
</li>
<li>Balanza analítica<br>
</li>
<li>Balones volumétricos<br>
</li>
<li>Estufa a 105°C<br>
</li>
<li>Éter de petróleo o éter dietílico<br>
</li>
<li>Cartuchos de cartón<br>
</li>
<li>Espátula, formulario, lapicero</li>
</ul>
</section>
<section id="procedimiento-de-extracto-etéreo" class="level3">
<h3 class="anchored" data-anchor-id="procedimiento-de-extracto-etéreo">Procedimiento de Extracto Etéreo</h3>
<ol type="1">
<li>Preparar los balones volumétricos</li>
<li>Colocar los balones en la estufa por 1 hora</li>
<li>Sacarlos y colocarlos en el desecador por 30 o 60 min</li>
<li>Pesar el balón vacío (Peso del balón)</li>
<li>Tomar un cartucho de cartón</li>
<li>Pesar aproximadamente ± 5 g de alimento (Peso de la muestra)</li>
<li>Colocar el cartucho en el extractor y verificar que la parte superior del cartucho sobrepase la parte superior del sifón</li>
<li>Colocar ± 160 ml de éter en el balón de 250 ml, previamente pesado.</li>
<li>Abrir el grifo de agua del refrigerante y encender las placas de calefacción</li>
<li>Hacer la extracción durante 6 a 8 h en función del tipo de alimento y la cantidad de grasa</li>
<li>Apagar las placas y desmontar el aparato cuando una cantidad máxima de éter se encuentra en el extractor. Quitar el cartucho y colocar el éter en la botella.</li>
<li>Montar de nuevo el aparato, encender las placas hasta que casi la totalidad del éter se encuentre en el extractor. Colocar el éter en la botella.</li>
<li>Colocar el balón en una estufa a 105 °C durante 1 h o una noche (dejar la puerta abierta durante 15 minutos para eliminar los vapores de éter)</li>
<li>Después de sacarlo de la estufa, se coloca en el desecador por 30 min y luego se pesa cuando esté frío (Peso del balón + EE)</li>
<li>Calcular el contenido en grasa o extracto etéreo</li>
</ol>
<p>Ejemplo de cálculo del <strong>pasto BORE</strong> <em>Alocasia macrorrhiza</em> con MS analítica - MSa = 95.3%</p>
<ul>
<li>Peso del balón = 111.3245g</li>
<li>Peso de muestra = 3.8867g</li>
<li>Peso del balón + EE = 111.3963g</li>
</ul>
<p>Ejemplo de cálculo:</p>
<p><span class="math display">\[
\%EE = \frac{\left( \text{Peso Balón} + EE \right) - \text{Peso Balón}}{\text{Peso muestra} \times MS_a} \times 100
\]</span></p>
<p><span class="math display">\[
\%EE = \frac{(111.3963g - 111.3245g)}{(3.8867g \times 0.953)} \times 100 = 1.93\%
\]</span></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/fig9-peso-balones-muestra.jpg" class="img-fluid figure-img"></p>
<figcaption>Figura 9. Peso de balones y de la muestra</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/fig10-peso-balon-extracto-etereo.jpg" class="img-fluid figure-img"></p>
<figcaption>Figura 10. Peso del balón con el Extracto Etéreo</figcaption>
</figure>
</div>
</section>
</section>
<section id="extracción-de-la-grasa-total" class="level2">
<h2 class="anchored" data-anchor-id="extracción-de-la-grasa-total">Extracción de la grasa total</h2>
<p>Una hidrólisis ácida es necesaria para muestras de productos lácteos, carnes, alimentos ricos en grasa (harina de pescado, soya, etc), materias fecales y todo tipo de materias que pueden contener grasa ligada.</p>
<section id="material-necesario-5" class="level3">
<h3 class="anchored" data-anchor-id="material-necesario-5">Material necesario</h3>
<ul>
<li>Beakers de 500 ml y vidrio de reloj (o refrigerante adecuado)</li>
<li>Placas de calefacción</li>
<li>Balanza analítica</li>
<li>Solución de HCl 3 N<br>
</li>
<li>Agua destilada</li>
<li>Embudos de 6-10 cm Ø</li>
<li>Filtros de papel</li>
<li>Bomba de vacío</li>
<li>Balanza 105°C</li>
</ul>
</section>
<section id="procedimiento-2" class="level3">
<h3 class="anchored" data-anchor-id="procedimiento-2">Procedimiento</h3>
<ul>
<li>Pesar precisamente en un beaker de 500 ml ± 2.5 g de alimento seco</li>
<li>Agregar 100 ml de HCl 3N y hervir durante 1 h bajo refrigerante o vidrio de reloj</li>
<li>Dejar enfriar y filtrar sobre doble papel filtro</li>
<li>Lavar abundantemente el residuo con agua destilada caliente hasta desaparición del ácido.</li>
<li>Desecar el filtro durante una noche a 105°C</li>
<li>Extraer la grasa por el método de Soxhlet y calcular la cantidad de grasa extraída.</li>
</ul>
</section>
</section>
<section id="anexo-4.-determinación-de-proteína-cruda" class="level2">
<h2 class="anchored" data-anchor-id="anexo-4.-determinación-de-proteína-cruda">Anexo 4. Determinación de Proteína Cruda</h2>
<p>Las proteínas son polímeros de aminoácidos. Es el único macro nutriente que contiene Nitrógeno, lo que le distingue de la grasa y los carbohidratos. La presencia de nitrógeno en las proteínas es muchas veces utilizada para estimar la cantidad de proteína bruta en un alimento. Como se considera que las proteínas contienen en promedio 16g N/100g, se determina el contenido en nitrógeno y se multiplica el resultado por 6.25 (100/16). El método todavía más utilizado en el mundo es el método de Kjeldahl.</p>
<section id="material-necesario-6" class="level3">
<h3 class="anchored" data-anchor-id="material-necesario-6">Material necesario</h3>
<ul>
<li>Balanza de precisión</li>
<li>Destilador<br>
</li>
<li>Digestor Büchi</li>
<li>Extractor de gases Büchi</li>
<li>Bureta</li>
<li>Probeta de 30-50 ml</li>
<li>Erlenmeyer 250 ml</li>
<li>Tubos Büchi</li>
<li>Pipetas</li>
<li>Agua destilada</li>
</ul>
</section>
<section id="reactivos" class="level3">
<h3 class="anchored" data-anchor-id="reactivos">Reactivos</h3>
<ul>
<li>Ácido sulfúrico H₂SO₄ (96-98%)</li>
<li>Hidróxido de sodio NaOH (32%)</li>
<li>Carbonato de sodio NaCO₃</li>
<li>Ácido bórico H₃BO₃ (2%)</li>
<li>Azul de timol</li>
<li>Indicador mixto: se prepara con rojo de metilo 0.40g y verde de bromocresol 0.60g. Disolución en etanol por separado, luego mezclarlos. Llevarlos a volumen de 100 ml</li>
<li>Catalizador: pueden ser Tabletas Kjeldahl o preparación en polvo del catalizador: 0.05g de óxido de selenio SeO + 2.5 g de sulfato de sodio Na₂SO₄, se revuelve hasta homogenizar (valor dado por muestra)</li>
<li>Ácido clorhídrico HCl ó Ácido sulfúrico H₂SO₄ 0.1 N</li>
</ul>
</section>
<section id="procedimiento-3" class="level3">
<h3 class="anchored" data-anchor-id="procedimiento-3">Procedimiento</h3>
<p>Pesaje de muestra y preparación para la digestión:</p>
<p>Se pesan aproximadamente 0.5g de muestra, se envuelven en papel toalla (Figura 11)</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/fig11-pesaje-muestra-nitrogeno.jpg" class="img-fluid figure-img"></p>
<figcaption>Figura 11. Pesaje de la muestra para la determinación de Nitrógeno</figcaption>
</figure>
</div>
<p>La determinación de la Proteína Cruda, midiendo inicialmente el Nitrógeno se realiza en tres etapas: Digestión, Destilación y Titulación</p>
</section>
<section id="etapa-1-digestión-o-hidrólisis" class="level3">
<h3 class="anchored" data-anchor-id="etapa-1-digestión-o-hidrólisis">Etapa 1: Digestión o hidrólisis</h3>
<p>Se le agregan 10 ml de H₂SO₄ al 96-98% + 1 tableta Kjeldahl (Figura 11) y se coloca en digestión por 30 a 45 minutos, permitiendo temperaturas de hasta 450ºC. (Figura 13).</p>
<p>En esta etapa, se convierte primero el nitrógeno en sulfato amónico. La muestra sufre un tratamiento con ácido sulfúrico concentrado (96-98 %) durante una hora a 450°C.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/fig12-preparacion-muestra-digestion.jpg" class="img-fluid figure-img"></p>
<figcaption>Figura 12. Preparación de la muestra para la digestión</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/fig13-digestion-campana-extraccion.jpg" class="img-fluid figure-img"></p>
<figcaption>Figura 13. Digestión en la campana de extracción</figcaption>
</figure>
</div>
</section>
<section id="etapa-2-destilación" class="level3">
<h3 class="anchored" data-anchor-id="etapa-2-destilación">Etapa 2: Destilación</h3>
<p>Hay liberación del amoniaco por alcalinización: se coloca el tubo con la muestra en el destilador y en un Erlenmeyer se miden 30 ml de ácido bórico al 2% al cual ya se le ha adicionado el indicador mixto.</p>
<p>Se lleva el Erlenmeyer al destilador de nitrógeno por debajo del tubo de salida del destilado.</p>
<p>Se programa el destilador para que adicione a la muestra NaOH al 32% (70 ml) y agua destilada (50 ml) durante 5 minutos.</p>
<p>En esta etapa de destilación, el sulfato de amonio se convierte en amoniaco en forma gaseosa (NH₃) por calentamiento, en presencia de hidróxido de sodio y de vapor de agua, el amoniaco se recupera por destilación sobre el ácido bórico y los indicadores mixtos que están en el Erlenmeyer.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/fig14-preparacion-proceso-destilacion.jpg" class="img-fluid figure-img"></p>
<figcaption>Figura 14. Preparación de la muestra para la destilación y proceso de destilación</figcaption>
</figure>
</div>
</section>
<section id="etapa-3-titulación" class="level3">
<h3 class="anchored" data-anchor-id="etapa-3-titulación">Etapa 3: Titulación</h3>
<p>Se lleva el Erlenmeyer con la muestra para la titulación con la bureta.</p>
<p>Titulación del borato de amonio formado con la solución de HCl o H₂SO₄ 0.1 N, usando como indicador rojo de metilo – verde bromocresol. La solución pasa de un color verde a un color original que tenía el ácido bórico con su respectivo indicador.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/fig15-titulacion-acido-sulfurico.jpg" class="img-fluid figure-img"></p>
<figcaption>Figura 15. Titulación con ácido sulfúrico</figcaption>
</figure>
</div>
<p>Cálculo de Nitrógeno en Materia Seca</p>
<p>Nitrógeno expresado en materia seca, titulando con H₂SO₄</p>
<p><span class="math display">\[
\%N = \frac{\text{ml } H_2SO_4 \times N \text{ del ácido} \times \text{m-eq de } N}{\text{peso de la muestra} \times MS_a} \times 100
\]</span> N - Normalidad del ácido = 0.1</p>
<p><span class="math display">\[
\text{m-eq } N \text{ (miliequivalentes de Nitrógeno)} = \left( \frac{\text{Peso molecular de } N}{1000} \right) = \left( \frac{14}{1000} \right) = 0.014
\]</span></p>
<p>Ejemplo de cálculo del <strong>pasto BORE</strong> <em>Alocasia macrorrhiza</em> con MS analítica - MSa = 95.3%</p>
<ul>
<li>Peso muestra = 0.5320g</li>
<li>Volumen gastado en la titulación = 12.32 ml</li>
</ul>
<p><span class="math display">\[
\% \text{Nitrógeno} = \frac{12.32 \times 0.1 \times 0.014}{0.5320 \times 0.953} \times 100 = 3.40\%
\]</span></p>
<p>Proteína Cruda:</p>
<p><span class="math display">\[
\%PC = \%N \times 6.25 = 3.40 \times 6.25 = 21.26\%
\]</span></p>
</section>
</section>
<section id="anexo-5.-análisis-de-van-soest" class="level2">
<h2 class="anchored" data-anchor-id="anexo-5.-análisis-de-van-soest">Anexo 5. Análisis de Van Soest</h2>
<p>En el análisis de Van Soest se miden tres fracciones:</p>
<ul>
<li>Fibra Detergente Neutra - FDN</li>
<li>Fibra Detergente Ácida - FDA</li>
<li>Lignina Detergente Ácida - LDA</li>
</ul>
<p>Se pueden estimar el contenido de hemicelulosa y celulosa de la pared celular:</p>
<p><span class="math display">\[
\text{Hemicelulosa} = \%FDN - \%FDA
\]</span></p>
<p><span class="math display">\[
\text{Celulosa} = \%FDA - \%LDA
\]</span></p>
<section id="determinación-de-la-fibra-detergente-neutra-fdn" class="level3">
<h3 class="anchored" data-anchor-id="determinación-de-la-fibra-detergente-neutra-fdn">Determinación de la Fibra Detergente Neutra – FDN</h3>
<p>Se pesa la muestra y se agrega la Solución Detergente Neutra que se encarga de eliminar el contenido citoplasmático (orgánico), quedando la pared celular y los minerales.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/fig16-fibra-detergente-neutra.jpg" class="img-fluid figure-img"></p>
<figcaption>Figura 16. Determinación de la Fibra Detergente Neutra.</figcaption>
</figure>
</div>
</section>
<section id="determinación-de-la-fibra-detergente-ácida-fda" class="level3">
<h3 class="anchored" data-anchor-id="determinación-de-la-fibra-detergente-ácida-fda">Determinación de la Fibra Detergente Ácida – FDA</h3>
<p>Después de obtener la pared celular y los minerales, se agrega Solución Detergente Ácida para eliminar la hemicelulosa, quedando la celulosa, lignina y minerales (Figura 17).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/fig17-fibra-detergente-acida.jpg" class="img-fluid figure-img"></p>
<figcaption>Figura 17. Determinación de Fibra Detergente Ácida</figcaption>
</figure>
</div>
</section>
<section id="determinación-de-lignina-lda" class="level3">
<h3 class="anchored" data-anchor-id="determinación-de-lignina-lda">Determinación de Lignina – LDA</h3>
<p>Después de obtener celulosa, lignina y minerales, se añade ácido sulfúrico al 72% para eliminar la celulosa, quedando lignina y minerales (Figura 18).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/fig18-lignina-detergente-acida.jpg" class="img-fluid figure-img"></p>
<figcaption>Figura 18. Determinación de Lignina Detergente Ácida</figcaption>
</figure>
</div>
</section>
<section id="ajuste-final-de-fdn-fda-y-lda" class="level3">
<h3 class="anchored" data-anchor-id="ajuste-final-de-fdn-fda-y-lda">Ajuste Final de FDN, FDA y LDA</h3>
<p>Posterior a estos tres pasos o determinaciones, se realiza la combustión de la lignina para ajustar las determinaciones de FDN, FDA y LDA, quitando los minerales de los residuos (Figura 19).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/fig19-cenizas-minerales.jpg" class="img-fluid figure-img"></p>
<figcaption>Figura 19. Determinación de cenizas o minerales de la muestra.</figcaption>
</figure>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/poetic-cocada-cf108f\.netlify\.app");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Creado por Resilient Technologies S.A.S <a href="https://restec.com.co/">ResTec</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Código fuente en <a href="https://github.com/ResTec-Col/website-labunal-palmira">GitHub</a></p>
</div>
  </div>
</footer>




</body></html>