project:
  type: website

website:
  title: "LABORATORIO DE NUTRICIÓN ANIMAL"
  favicon: img/logo-unal.svg
  navbar:
    logo: img/UNAL_Logosimbolo.svg
    left:
      - href: index.qmd
        text: Inicio
      - text: Guías laboratorio
        menu: 
          - href: data/plantilla.xlsx
            text: Plantilla registro de datos (Excel)
          - href: guias/analisis-alimentos-y-forrajes.qmd
          - href: guias/guia-composicion-quimica-alimentos.qmd
      - href: https://app-labunal-palmira-1042514922887.us-central1.run.app
        text: App
        target: _blank
        
  page-footer: 
    right: "Código fuente en <a href='https://github.com/ResTec-Col/website-labunal-palmira' target='_blank'>GitHub</a>"
    left: "&copy; Creado por Laboratorio Nutrición UNAL Palmira y <a href='https://restec.com.co/' target='_blank'>Resilient Technologies S.A.S</a>"

format:
  html:
    css: styles.css
    lang: es
    
    include-in-header:
      text: |
        <meta name="viewport" content="width=device-width, initial-scale=1.0">



